export const createContentRootPart1 = (runtime) => ({
  name: "TradeModalContent",
  components: {
    ShopView: runtime.ShopView,
    TemplateEditor: runtime.TemplateEditor,
    DefaultStackView: runtime.DefaultStackView,
    TrashBinView: runtime.TrashBinView,
    ShopEditor: runtime.ShopEditor,
    AssortmentManager: runtime.AssortmentManager,
    QuickTransferPreview: runtime.QuickTransferPreview,
    FlankActionButtons: runtime.FlankActionButtons,
    CurrencyDisplay: runtime.CurrencyDisplay,
    TradeModalDialogs: runtime.TradeModalDialogs,
    FieldEditDialog: runtime.FieldEditDialog,
    IconClassDialog: runtime.IconClassDialog,
    ItemDetailDialog: runtime.ItemDetailDialog,
    OwnerOptionDialog: runtime.OwnerOptionDialog,
    SuggestionDetailDialog: runtime.SuggestionDetailDialog,
    AssortmentMergeDialog: runtime.AssortmentMergeDialog,
    ShopActivationDialog: runtime.ShopActivationDialog,
    ViewSettingsDialog: runtime.ViewSettingsDialog,
    WeaponStatsDialog: runtime.WeaponStatsDialog,
  },
  provide() {
    // Expose full modal context for deeply nested view components via inject.
    return {
      [runtime.tradeModalContextKey]: this,
    };
  },
  emits: [
    "update:assortmentLeftContainerId",
    "update:assortmentSearch",
    "update:assortmentLeftTab",
    "update:gmMoveItemKey",
    "update:gmMoveTargetContainerId",
    "update:gmMoveQuantity",
    "update:assortmentRightContainerId",
    "update:assortmentRightTab",
    "update:shopBuyContainerId",
    "update:shopBuyItemKey",
    "update:shopBuyTargetContainerId",
    "update:shopBuyQuantity",
    "update:trashZoneOwnerCode",
    "update:inventoryOwnerCodeFilter",
    "update:iconSize",
    "update:itemDetailNickname",
    "update:suggestionDetailVariantId",
    "update:inventoryForm",
    "update:templateForm",
    "update:newTemplateForm",
    "left-flank-action",
    "right-flank-action",
    "undo-container-action",
    "toggle-container-selection",
    "move-container-selection",
    "gm-move",
    "shop-buy",
    "buy-item-click",
    "buy-item-quantity-step",
    "buy-item-quantity-set",
    "sell-item-click",
    "sell-item-quantity-step",
    "sell-item-quantity-set",
    "buy-action",
    "sell-action",
    "delete-template",
    "open-class-edit",
    "apply-class-edit",
    "confirm-class-edit",
    "close-field-edit-dialog",
    "update-class-edit-draft-value",
    "update-class-edit-search",
    "apply-class-edit-suggestion",
    "start-template-create",
    "reset-new-template-form",
    "close-class-edit-dialog",
    "close-weapon-stats-dialog",
    "create-weapon-stats",
    "remove-weapon-stats",
    "select-weapon-stats-item",
    "update-weapon-stats-draft",
    "confirm-weapon-stats",
    "select-img-class",
    "confirm-img-class",
    "close-owner-opt-dialog",
    "select-owner-opt",
    "confirm-owner-opt",
    "open-item-detail-dialog",
    "close-item-detail-dialog",
    "apply-item-detail-nickname",
    "toggle-item-detail-nickname-mode",
    "open-suggestion-detail-dialog",
    "close-suggestion-detail-dialog",
    "confirm-suggestion-detail-action",
    "close-view-settings-dialog",
  ],
  data() {
    return {
      localInventoryForm: {},
      localTemplateForm: {},
      localNewTemplateForm: {},
      syncingForms: false,
      imgClassSearch: "",
      imgClassTypeFilter: "all",
      imgClassSubtypeFilter: "all",
      imgClassSortMode: "asc",
      iconMetadataMap: {},
      iconCollectionChanges: {
        added: {},
        removed: [],
        remap: {},
      },
      selectedIconMetadataDraft: null,
      selectedIconClassDraft: "",
      newIconClassDraft: "",
      iconCatalogValidationError: "",
      draggedIconClass: "",
      dragOverIconClass: "",
      buyTypeFilter: "all",
      sellTypeFilter: "all",
      buyTypeSearch: "",
      sellTypeSearch: "",
      buySortMode: "name",
      sellSortMode: "name",
      mobileTradeTab: "buy",
      viewSettingsIconSizeDraft: 34,
      iconMetadataCacheStamp: 0,
      tradeItemTypeKeyCache: runtime.markRaw(new Map()),
    };
  },
  mounted() {
    this.loadIconCollectionChanges();
    this.loadIconMetadataMap();
  },
});
