export const WALL_PRESETS = Object.freeze({
  solid: Object.freeze({
    type: "wall",
    wallType: "solid",
    doorType: "none",
    restrictionType: "normal",
    blocksMovement: true,
    blocksSight: true,
    blocksLight: true,
    blocksSound: true,
  }),
  terrain: Object.freeze({
    type: "terrain",
    wallType: "terrain",
    doorType: "none",
    restrictionType: "limited",
    blocksMovement: true,
    blocksSight: true,
    blocksLight: true,
    blocksSound: true,
  }),
  invisible: Object.freeze({
    type: "invisible",
    wallType: "invisible",
    doorType: "none",
    restrictionType: "normal",
    blocksMovement: true,
    blocksSight: false,
    blocksLight: false,
    blocksSound: false,
  }),
  ethereal: Object.freeze({
    type: "ethereal",
    wallType: "ethereal",
    doorType: "none",
    restrictionType: "normal",
    blocksMovement: false,
    blocksSight: true,
    blocksLight: true,
    blocksSound: false,
  }),
  door: Object.freeze({
    type: "door",
    wallType: "solid",
    doorType: "door",
    restrictionType: "normal",
    doorState: "closed",
    blocksMovement: true,
    blocksSight: true,
    blocksLight: true,
    blocksSound: true,
  }),
  secret: Object.freeze({
    type: "secret",
    wallType: "solid",
    doorType: "secret",
    restrictionType: "normal",
    doorState: "closed",
    blocksMovement: true,
    blocksSight: true,
    blocksLight: true,
    blocksSound: true,
  }),
  window: Object.freeze({
    type: "window",
    wallType: "solid",
    doorType: "window",
    restrictionType: "proximity",
    doorState: "closed",
    proximityThreshold: 10,
    blocksMovement: true,
    blocksSight: false,
    blocksLight: false,
    blocksSound: true,
  }),
});

export const wallPreset = (name) => ({
  ...(WALL_PRESETS[name] ||
    Object.values(WALL_PRESETS).find((preset) => preset.type === name) ||
    WALL_PRESETS.solid),
});
