export const shopProfileArchetypes = [
  {
    id: "guildWorkshop",
    icon: "⚒",
    values: {
      typeId: "sklad_cechowy",
      locationType: "dzielnica_rzemieslnicza",
      legalStatus: "licensed",
      wealthTier: "standard",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 5,
    },
  },
  {
    id: "marketStall",
    icon: "⚖",
    values: {
      typeId: "kram",
      locationType: "rynek",
      legalStatus: "legal",
      wealthTier: "biedny",
      reputation: "neutralna",
      seasonality: "jarmark",
      counterfeitRisk: 15,
    },
  },
  {
    id: "merchantHouse",
    icon: "◆",
    values: {
      typeId: "dom_kupiecki",
      locationType: "dzielnica_kupiecka",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 8,
    },
  },
  {
    id: "courtSupplier",
    icon: "♜",
    values: {
      typeId: "zlotnik",
      locationType: "zamek",
      legalStatus: "licensed",
      wealthTier: "elitarny",
      reputation: "znakomita",
      seasonality: "caloroczny",
      counterfeitRisk: 10,
    },
  },
  {
    id: "itinerantTrader",
    icon: "☼",
    values: {
      typeId: "kramarz_wedrowny",
      locationType: "trakt",
      legalStatus: "mixed",
      wealthTier: "standard",
      reputation: "neutralna",
      seasonality: "sezonowy",
      counterfeitRisk: 28,
    },
  },
  {
    id: "fence",
    icon: "◐",
    values: {
      typeId: "paserska_komora",
      locationType: "przedmiescie",
      legalStatus: "grey",
      wealthTier: "biedny",
      reputation: "podejrzana",
      seasonality: "caloroczny",
      counterfeitRisk: 62,
    },
  },
  {
    id: "apothecary",
    icon: "✚",
    values: {
      typeId: "aptekarz",
      locationType: "miasto",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 8,
    },
  },
  {
    id: "roadsideInn",
    icon: "⌂",
    values: {
      typeId: "zajazd",
      locationType: "trakt",
      legalStatus: "legal",
      wealthTier: "standard",
      reputation: "neutralna",
      seasonality: "caloroczny",
      counterfeitRisk: 22,
    },
  },
  {
    id: "portWarehouse",
    icon: "▦",
    values: {
      typeId: "sklad_towarow",
      locationType: "port",
      legalStatus: "mixed",
      wealthTier: "bogaty",
      reputation: "neutralna",
      seasonality: "caloroczny",
      counterfeitRisk: 36,
    },
  },
  {
    id: "monasticScriptorium",
    icon: "✒",
    values: {
      typeId: "skryptorium",
      locationType: "klasztor",
      legalStatus: "licensed",
      wealthTier: "standard",
      reputation: "znakomita",
      seasonality: "caloroczny",
      counterfeitRisk: 2,
    },
  },
  {
    id: "armourer",
    icon: "♜",
    values: {
      typeId: "platnerz",
      locationType: "dzielnica_rzemieslnicza",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 6,
    },
  },
  {
    id: "clothMerchant",
    icon: "▧",
    values: {
      typeId: "sukiennik",
      locationType: "dzielnica_kupiecka",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 8,
    },
  },
  {
    id: "saltMerchant",
    icon: "◇",
    values: {
      typeId: "sklad_soli",
      locationType: "port",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 9,
    },
  },
  {
    id: "moneyChanger",
    icon: "¤",
    values: {
      typeId: "kantor",
      locationType: "dzielnica_kupiecka",
      legalStatus: "licensed",
      wealthTier: "elitarny",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 18,
    },
  },
  {
    id: "printHouse",
    icon: "¶",
    values: {
      typeId: "drukarz",
      locationType: "miasto",
      legalStatus: "licensed",
      wealthTier: "bogaty",
      reputation: "dobra",
      seasonality: "caloroczny",
      counterfeitRisk: 6,
    },
  },
];
