export const profileLocationOptions = [
  "dzielnica_kupiecka",
  "dzielnica_rzemieslnicza",
  "rynek",
  "miasto",
  "przedmiescie",
  "port",
  "zamek",
  "klasztor",
  "wies",
  "trakt",
  "jarmark",
];

export const lateMedievalTypeSuggestions = [
  {
    id: "dom_kupiecki",
    icon: "◆",
    locations: ["dzielnica_kupiecka", "port"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["bogaty", "elitarny"],
  },
  {
    id: "kram",
    icon: "⚖",
    locations: ["rynek", "jarmark", "miasto"],
    legalStatuses: ["legal"],
    wealthTiers: ["biedny", "standard"],
  },
  {
    id: "sklad_cechowy",
    icon: "⚒",
    locations: ["dzielnica_rzemieslnicza", "miasto"],
    legalStatuses: ["licensed"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "aptekarz",
    icon: "✚",
    locations: ["miasto", "klasztor", "dzielnica_kupiecka"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "platnerz",
    icon: "♜",
    locations: ["dzielnica_rzemieslnicza", "zamek", "miasto"],
    legalStatuses: ["licensed"],
    wealthTiers: ["bogaty", "elitarny"],
  },
  {
    id: "sukiennik",
    icon: "▧",
    locations: ["dzielnica_kupiecka", "rynek", "miasto"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "korzennik",
    icon: "✦",
    locations: ["dzielnica_kupiecka", "port", "rynek"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["bogaty", "elitarny", "luksusowy"],
  },
  {
    id: "zlotnik",
    icon: "♛",
    locations: ["zamek", "dzielnica_kupiecka"],
    legalStatuses: ["licensed"],
    wealthTiers: ["elitarny", "luksusowy"],
  },
  {
    id: "skryptorium",
    icon: "✒",
    locations: ["klasztor", "zamek", "miasto"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "drukarz",
    icon: "¶",
    locations: ["miasto", "dzielnica_kupiecka"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["bogaty", "elitarny"],
  },
  {
    id: "kantor",
    icon: "¤",
    locations: ["dzielnica_kupiecka", "port", "rynek"],
    legalStatuses: ["licensed", "mixed"],
    wealthTiers: ["bogaty", "elitarny"],
  },
  {
    id: "zajazd",
    icon: "⌂",
    locations: ["trakt", "przedmiescie", "wies"],
    legalStatuses: ["legal", "licensed"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "sklad_towarow",
    icon: "▦",
    locations: ["port", "dzielnica_kupiecka", "przedmiescie"],
    legalStatuses: ["legal", "mixed"],
    wealthTiers: ["standard", "bogaty"],
  },
  {
    id: "sklad_soli",
    icon: "◇",
    locations: ["port", "dzielnica_kupiecka", "rynek"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["bogaty"],
  },
  {
    id: "piekarnia",
    icon: "◒",
    locations: ["miasto", "rynek", "wies"],
    legalStatuses: ["legal", "licensed"],
    wealthTiers: ["biedny", "standard"],
  },
  {
    id: "kowal",
    icon: "⚒",
    locations: ["dzielnica_rzemieslnicza", "wies", "przedmiescie"],
    legalStatuses: ["licensed", "legal"],
    wealthTiers: ["biedny", "standard"],
  },
  {
    id: "paserska_komora",
    icon: "◐",
    locations: ["przedmiescie", "port", "miasto"],
    legalStatuses: ["grey", "illegal", "mixed"],
    wealthTiers: ["biedny", "standard"],
  },
  {
    id: "sklad_kontrabandy",
    icon: "☠",
    locations: ["port", "przedmiescie", "trakt"],
    legalStatuses: ["illegal", "grey"],
    wealthTiers: ["standard", "bogaty"],
  },
];
