export const emptySceneWorkspaceState = () => ({
  scenes: [],
  selectedSceneId: null,
  selectedTokenId: null,
  selectedTokenIds: [],
  targetedTokenIds: [],
  movementRequests: [],
  movementRequestCapabilities: { canResolve: false },
  movementRequestPhase: "idle",
  combatByScene: {},
  combatCapabilitiesByScene: {},
  combatPhase: "idle",
  combatError: null,
  activeSceneId: null,
  capabilities: { canManage: false, canViewHidden: false },
  phase: "idle",
  error: null,
  unauthorized: false,
});
