export const TABLE_UTILITIES = Object.freeze([
  {
    id: "chat",
    icon: "chat",
    labelKey: "vtt.table.rail.chat",
    windowWidth: 529,
    windowHeight: 530,
    aspectRatio: 529 / 530,
    centered: true,
    constrainToViewport: true,
    windowType: "chat",
  },
  {
    id: "combat",
    icon: "sword",
    labelKey: "vtt.table.rail.combat",
    windowWidth: 520,
    windowHeight: 760,
  },
  { id: "graphics", icon: "image", labelKey: "vtt.table.rail.graphics" },
  {
    id: "characters",
    icon: "users",
    labelKey: "vtt.table.rail.characters",
    windowWidth: 1480,
    windowHeight: 900,
  },
  {
    id: "professions",
    icon: "book",
    labelKey: "vtt.table.rail.professions",
    windowWidth: 1120,
    windowHeight: 760,
    minWindowWidth: 680,
    minWindowHeight: 500,
    maxWindowWidth: 1440,
    maxWindowHeight: 920,
    maxViewportWidthRatio: 0.94,
    maxViewportHeightRatio: 0.92,
    resizable: true,
    maximizable: true,
    constrainToViewport: true,
    centered: true,
    windowType: "professions",
  },
  { id: "items", icon: "package", labelKey: "vtt.table.rail.items" },
  {
    id: "journal",
    icon: "book",
    labelKey: "vtt.table.rail.journal",
    windowWidth: 1180,
    windowHeight: 720,
    minWindowWidth: 760,
    minWindowHeight: 520,
    maxViewportWidthRatio: 0.95,
    maxViewportHeightRatio: 0.9,
    resizable: true,
    constrainToViewport: true,
    centered: true,
    windowType: "journal",
    windowOnly: true,
  },
  {
    id: "calendar",
    icon: "calendar",
    labelKey: "vtt.table.rail.calendar",
    windowWidth: 1050,
    windowHeight: 720,
    minWindowWidth: 760,
    minWindowHeight: 520,
    maxWindowWidth: 1320,
    maxWindowHeight: 900,
    maxViewportWidthRatio: 0.96,
    maxViewportHeightRatio: 0.94,
    resizable: true,
    maximizable: true,
    constrainToViewport: true,
    centered: true,
    directWindow: true,
    windowType: "calendar",
  },
  {
    id: "handouts",
    icon: "file",
    labelKey: "vtt.table.rail.handouts",
    windowWidth: 1120,
    windowHeight: 780,
  },
  { id: "scenario", icon: "book", labelKey: "vtt.table.rail.scenario" },
  { id: "scenes", icon: "scene", labelKey: "vtt.table.rail.scenes" },
  {
    id: "token-sync",
    icon: "chain",
    labelKey: "vtt.table.rail.tokenSync",
    windowWidth: 980,
    windowHeight: 760,
    minWindowWidth: 720,
    minWindowHeight: 520,
    maxWindowWidth: 1440,
    maxWindowHeight: 980,
    resizable: true,
    windowOnly: true,
  },
  {
    id: "token-templates",
    icon: "token",
    labelKey: "vtt.table.rail.tokenTemplates",
    windowWidth: 760,
    windowHeight: 720,
    minWindowWidth: 420,
    minWindowHeight: 480,
    maxWindowWidth: 1200,
    maxWindowHeight: 960,
    resizable: true,
  },
  { id: "tables", icon: "dice", labelKey: "vtt.table.rail.tables" },
  {
    id: "shop",
    icon: "shop",
    labelKey: "vtt.table.rail.shop",
    windowWidth: 1180,
    windowHeight: 780,
  },
  {
    id: "voice",
    icon: "microphone",
    labelKey: "vtt.table.rail.voice",
    windowHeight: 720,
  },
  {
    id: "jukebox",
    icon: "music",
    labelKey: "vtt.table.rail.jukebox",
    windowHeight: 840,
  },
  {
    id: "sound-effects",
    icon: "audio-waveform",
    labelKey: "vtt.table.rail.soundEffects",
    windowWidth: 1180,
    windowHeight: 760,
    minWindowWidth: 860,
    minWindowHeight: 560,
    maxWindowWidth: 1540,
    maxWindowHeight: 980,
    resizable: true,
  },
  {
    id: "compendium",
    icon: "database",
    labelKey: "vtt.table.rail.compendium",
    windowWidth: 1480,
    windowHeight: 920,
    fillViewport: true,
  },
  {
    id: "notifications",
    icon: "bell",
    labelKey: "vtt.table.rail.notifications",
  },
  {
    id: "settings",
    icon: "settings",
    labelKey: "vtt.table.rail.settings",
    drawerOnly: true,
  },
]);

export const IMPLEMENTED_TABLE_UTILITIES = Object.freeze([
  "chat",
  "combat",
  "graphics",
  "characters",
  "professions",
  "calendar",
  "handouts",
  "compendium",
  "scenario",
  "scenes",
  "token-templates",
  "shop",
  "voice",
  "jukebox",
  "sound-effects",
  "notifications",
  "settings",
]);

export const utilityById = (id) =>
  TABLE_UTILITIES.find((utility) => utility.id === id) || null;
