export const createVttState = () => ({
  campaignId: null,
  scenes: [],
  activeSceneId: null,
  selectedSceneId: null,
  tokensByScene: {},
  tokenCapabilitiesByScene: {},
  selectedTokenId: null,
  selectedTokenIds: [],
  targetedTokenIds: [],
  tokenPhase: "idle",
  tokenSyncCatalog: {
    scenes: [],
    tokens: [],
    links: [],
    syncFields: [],
    capabilities: { canManage: false },
  },
  tokenSyncPhase: "idle",
  tokenSyncError: null,
  movementRequests: [],
  movementRequestCapabilities: { canResolve: false },
  movementRequestPhase: "idle",
  combatByScene: {},
  combatCapabilitiesByScene: {},
  combatPhase: "idle",
  combatError: null,
  wallsByScene: {},
  wallCapabilitiesByScene: {},
  selectedWallId: null,
  wallPhase: "idle",
  lightsByScene: {},
  lightCapabilitiesByScene: {},
  selectedLightId: null,
  lightPhase: "idle",
  regionsByScene: {},
  regionCapabilitiesByScene: {},
  selectedRegionId: null,
  regionPhase: "idle",
  tilesByScene: {},
  tileCapabilitiesByScene: {},
  selectedTileId: null,
  tilePhase: "idle",
  fogBySceneUser: {},
  selectedFogUserId: null,
  fogPhase: "idle",
  sceneLoading: {
    active: false,
    sceneId: null,
    detail: "",
    steps: [],
  },
  capabilities: {
    canManage: false,
    canViewHidden: false,
  },
  phase: "idle",
  error: null,
  unauthorized: false,
  requestId: 0,
});
