export const createVttState = () => ({
  campaignId: null,
  scenes: [],
  activeSceneId: null,
  selectedSceneId: null,
  tokensByScene: {},
  tokenCapabilitiesByScene: {},
  selectedTokenId: null,
  selectedTokenIds: [],
  tokenPhase: "idle",
  wallsByScene: {},
  wallCapabilitiesByScene: {},
  selectedWallId: null,
  wallPhase: "idle",
  lightsByScene: {},
  lightCapabilitiesByScene: {},
  selectedLightId: null,
  lightPhase: "idle",
  tilesByScene: {},
  tileCapabilitiesByScene: {},
  selectedTileId: null,
  tilePhase: "idle",
  capabilities: {
    canManage: false,
    canViewHidden: false,
  },
  phase: "idle",
  error: null,
  unauthorized: false,
  requestId: 0,
});
