export const createVttState = () => ({
  campaignId: null,
  scenes: [],
  activeSceneId: null,
  selectedSceneId: null,
  tokensByScene: {},
  tokenCapabilitiesByScene: {},
  selectedTokenId: null,
  selectedTokenIds: [],
  targetedTokenIds: [],
  tokenPhase: "idle",
  movementRequests: [],
  movementRequestCapabilities: { canResolve: false },
  movementRequestPhase: "idle",
  combatByScene: {},
  combatCapabilitiesByScene: {},
  combatPhase: "idle",
  combatError: null,
  wallsByScene: {},
  wallCapabilitiesByScene: {},
  selectedWallId: null,
  wallPhase: "idle",
  lightsByScene: {},
  lightCapabilitiesByScene: {},
  selectedLightId: null,
  lightPhase: "idle",
  tilesByScene: {},
  tileCapabilitiesByScene: {},
  selectedTileId: null,
  tilePhase: "idle",
  fogBySceneUser: {},
  selectedFogUserId: null,
  fogPhase: "idle",
  capabilities: {
    canManage: false,
    canViewHidden: false,
  },
  phase: "idle",
  error: null,
  unauthorized: false,
  requestId: 0,
});
