<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class WarhammerDataSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();
        $sysBuilder = $db->table('rpg_systems');

        // 1. Pobierz ID systemu WFRP 2ed
        // Zakładamy, że RpgInitializationSeeder już go stworzył, ale dla bezpieczeństwa sprawdzamy.
        $systemCode = 'wfrp2ed';
        $system = $sysBuilder->where('code', $systemCode)->get()->getRow();
        
        if (!$system) {
            echo "⚠️ Nie znaleziono systemu '$systemCode'. Tworzę go awaryjnie...\n";
            $sysBuilder->insert([
                'code'        => $systemCode,
                'name'        => 'Warhammer Fantasy Roleplay 2ed',
                'description' => 'Ponury świat niebezpiecznych przygód.',
                'created_at'  => date('Y-m-d H:i:s')
            ]);
            $systemId = $db->insertID();
        } else {
            $systemId = $system->id;
        }

        echo "🔧 Importowanie szczegółowych danych (Skills/Talents) dla WFRP 2ed (ID: $systemId)...\n";

        // 2. Import Umiejętności
        $skills = $this->getWfrpSkills();
        $this->migrujKategorie($db, $systemId, 'umiejetnosc', $skills, function($row) {
            return [
                'name'        => $row[1],
                'description' => isset($row[4]) ? $row[4] : '',
                'metadata'    => json_encode([
                    'typ'       => isset($row[2]) ? $row[2] : 'Podstawowa',
                    'cecha'     => isset($row[3]) ? $row[3] : '',
                    'powiazane' => isset($row[5]) ? $row[5] : '',
                    'koszt_xp'  => isset($row[6]) ? $row[6] : 0,
                    'mechanika' => isset($row[7]) ? $row[7] : ''
                ])
            ];
        });

        // 3. Import Zdolności
        $talents = $this->getWfrpTalents();
        $this->migrujKategorie($db, $systemId, 'zdolnosc', $talents, function($row) {
            return [
                'name'        => $row[1],
                'description' => isset($row[2]) ? $row[2] : '',
                'metadata'    => json_encode([
                    'efekt'       => isset($row[3]) ? $row[3] : '',
                    'modyfikator' => isset($row[4]) ? $row[4] : '',
                    'talent'      => isset($row[5]) ? $row[5] : ''
                ])
            ];
        });
    }

    /**
     * Pomocnicza funkcja do importowania danych kategoriami.
     */
    private function migrujKategorie($db, $systemId, $category, $rows, $mapper)
    {
        $builder = $db->table('game_definitions');
        $count = 0;

        foreach ($rows as $row) {
            $data = $mapper($row);
            $data['system_id'] = $systemId;
            $data['category']  = $category;
            $data['created_at'] = date('Y-m-d H:i:s');

            // Sprawdzamy duplikaty po nazwie, systemie i kategorii
            $exists = $builder->where('system_id', $systemId)
                              ->where('category', $category)
                              ->where('name', $data['name'])
                              ->countAllResults();

            if ($exists == 0) {
                $builder->insert($data);
                $count++;
            }
        }
        echo "✅ Zaimportowano $count rekordów do kategorii: '$category'.\n";
    }

    // ==========================================
    // DANE (Przeniesione do metod dla czystości kodu)
    // ==========================================

    private function getWfrpSkills()
    {
        return [
            [1, 'Brzuchomówstwo', 'Zaawansowana', 'Ogłada', 'Bohater potrafi mówić bez otwierania ust. Osoby uważnie obserwujące Bohatera korzystającego z tej umiejętności mogą wykonać test spostrzegawczości przeciwko testowi brzuchonrówstwa BG, żeby wykryć sztuczkę Bohatera.', 'brak', '100', ''],
            [2, 'Charakteryzacja', 'Podstawowa', 'Ogłada', 'Wykorzystanie tej umiejętności pozwala Bohaterowi maskować jego prawdziwy wygląd i udawać kogoś innego. Często potrzebne są dodatkowe rekwizyty, właściwe ubranie lub peruka. Dzięki tej umiejętności Bohater może przebrać się za przedstawiciela innej rasy, osobę płci przeciwnej, a nawet kogoś sławnego i znanego w całym kraju, choć tego rodzaju charakteryzacja jest znacznie trudniejsza. Przeciwko charakteryzacji często wykorzystuje się test spostrzegawczości przeciwnika.', 'naśladowca', '100', ''],
            [3, 'Czytanie i pisanie', 'Zaawansowana', 'Inteligencja', 'Bohater potrafi czytać i pisać w dowolnym języku, którym umie nę potługiwać. W większości przypadków czytania i pisania nit trzeba testować. Mistrz. Gry może jednak zdecydować, że test umiejętności jest potrzebny przy odcyfrowywaniu rękopisu spisanego w starożytnym języku, lub zawierającym niezrozumiałe wyrażenia albo archaiczne słownictwo.', 'poliglota', '100', ''],
            [4, 'Czytanie z warg', 'Zaawansowana', 'Inteligencja', 'Dzięki tej umiejętności Bohater może zrozumieć rozmowy prowadzone poza zasięgiem jego słuchu lub gdy rozmowa jest zagłuszana przez jakieś odgłosy. Musi widzieć usta obserwowanej osoby, jak również znać język, w którym prowadzona jest rozmowa.', 'bystry wzrok', '100', ''],
            [5, 'Dowodzenie', 'Podstawowa', 'Ogłada', 'Korzystający z tej umiejętności Bohater cieszy się posłuchem u podwładnych. Po udanym teście umiejętności podwładni dokładnie wypełniają jego polecenia. Nieudany test powoduje, że rozkaz zostaje wypełniony błędnic lub też nie zostaje wykonany w ogóle (zależnie od decyzji Mistrza Gry). Dowcdzcnic nie ma wpływu na zachow-anie osób postronnych, umożliwia posłuszeństwo osób podlegających władzy Bohatera.', 'brak', '100', ''],
            [6, 'Gadanina', 'Zaawansowana', 'Ogłada', 'Bohaterowie posiadający tę umiejętność mogą próbować zagadać osobę, zasypując ją potokiem słów. Korzystający z tej umiejętności Bohater zazwyczaj nie próbuje na nikogo wpływać (do tego służy przekonywanie), chce po prostu zyskać na czasie. Po udanym teście umiejętności gadanina ofiara ma prawo do testu Siły Woli, który określa, czy zorientowała się w tym, co się naprawdę dzieje. Nieudany test oznacza, że „zagadana” osoba nic nie robi przez całą rundę, zastanawiając się czy ma do czynienia z osobnikiem pijanym czy zwykłym idiotą, a może jedno i drugie. Gadanina nie przynosi rezultatu, jeśli ofiara bierze udział w walce lub stoi w obliczu ewidentnego zagrożenia życia. Bohater może próbować zagadać kilka osób (jedna osoba za każde 10 punktów jego Ogłady), pod warunkiem, że wszystkie te osoby rozumieją język, którym się posługuje.', 'brak', '100', ''],
            [7, 'Hazard', 'Podstawowa', 'Inteligencja', 'Umiejętność hazardu zwiększa szansę Bohatera na wygraną w grach losowych, takich jak karty łub kości. Każda uczestnicząca w grze postać wpłaca stawkę, a potem wszyscy grający jednocześnie wykonują test hazardu. Najniższy wynik rzutu (oczywiście, przy udanym teście) oznacza wygranie puli.', 'geniusz arytmetyczny', '100', ''],
            [8, 'Hipnoza', 'Zaawansowana', 'Siła Woli', 'Używając hipnozy Bohater może wprowadzić inną osobę w trans. Uwaga hipnotyzowanej osoby musi być przez minutę skupiona na jednej rzeczy (często wykorzystuje się jakąś błyskotkę na łańcuszku lub zapaloną świecę). Potem należy wykonać test umiejętności. Osoby próbujące opierać się hipnozie mogą wykonać test Siły Woli. Po wprowadzeniu osoby w trans. Bohater może jej zadać jedno pytanie za każde 10 punktów swojej Siły Woli. Osoba udziela odpowiedzi szczerze, zgodnie ze swoją wiedzą. Jeśli głęboko w coś wierzy, to udzieli takiej właśnie informacji. Po udzieleniu odpowiedzi na ostatnie pytanie osoba wychodzi z transu.', 'brak', '100', ''],
            [9, 'Jeździectwo', 'Podstawowa', 'Zręczność', 'Bohater potrafi jeździć konno lub na innych wierzchowcach. Zwykłe jeżdżenie w normalnych warunkach nie wymaga wykonywania testu umiejętności. Jednakże może on być konieczny w przypadku jazdy galopem, wyścigu, podczas jazdy w trudnym terenie wskakiwaniu na konia w biegu, itp..', 'woltyżerka', '100', ''],
            [10, 'Język tajemny', 'Zaawansowana', 'Inteligencja', 'Dzięki tej umiejętności Bohater może rzucać zaklęcia. Znajomość języka tajemnego jest konieczna przy używaniu magicznych formuł. W odróżnieniu od innych języków, język tajemny nie jest używany w codziennych rozmowach, a wyłącznie do manipulowania mocą magiczną. Wszystkie magiczne pergaminy i księgi zapisane są w określonym języku tajemnym. Istnieje wiele języków tajemnych. Najczęściej używane to: demoniczny, magiczny (znany wśród uczonych w Imperium pod nazwą Lingua Praettantia) i tajemny elfi.', 'brak', '100', ''],
            [11, 'Kuglarstwo (różne)', 'Zaawansowana', 'Ogłada', 'Kuglarstwo wykorzystywane jest do zabawiania publiczności. Podobnie jak w przypadku nauki i wiedzy, nazwa kuglarstwo określa kategorię oddzielnych umiejętności. Najczęściej spotykanymi rodzajami kuglarstwa są: akrobatyka, aktorstwo, błaznowanie, gawędziarstwo, komedianctwo, mimika, muzykalność, połykanie ognia, śpiew, taniec, wróżenie z dłoni, żonglerka', 'człowiek-guma, naśladowca', '100', ''],
            [12, 'Leczenie', 'Zaawansowana', 'Inteligencja', 'Dzięki tej umiejętności Bohater może zapewnić opiekę medyczną rannej osobie. Udany test leczenia przywraca lk O punktów Żywotności w przypadku osoby lekko rannej lub 1 punkt Żywotności w przypadku osoby ciężko rannej. Ranna osoba może być leczona tylko raz podczas sytuacji krytycznej (bitwa, zasadzka, pułapka, upadek, itp.). która spowodował: utratę punktów Żywotności, lub zaraz po niej. Test leczenia można ponowić następnego dnia, jak również, każdego kolejnego dnia Szczegółowe zasady leczenia ran znajdziesz w Rozdziale VI: Walka, obrażenia i ruch.', 'chirurgia', '100', ''],
            [13, 'Mocna głowa', 'Podstawowa', 'Odporność', 'Ta umiejętność zwiększa odporność Bohatera na alkohol. Doświadczeni poszukiwacze przygód potrafią sporo wypić i jednocześnie zachować względną trzeźwość. Test umiejętności wykonuje się po każdej porcji wypitego alkoholu. Więcej informacji o napojach alkoholowych i skutkach ich spożycia znajdziesz w Rozdziale V: Ekwipunek.', 'brak', '100', ''],
            [14, 'Nauka (różne)', 'Zaawansowana', 'Inteligencja', 'Ta umiejętność wykorzystywana jest do zapamiętywania ważniejszych informacji i liczb, jak też. (gdy Bohater posiada materiały pomocnicze i odpowiednie zasoby) do badań naukowych. Wymaga intensywnych studiów, lecz, zapewnia znacznie szerszą i jednocześnie bardziej szczegółową znajomość problemu niż w przypadku wiedzy ogólnej. Nauka nie jest pojedynczą umiejętnością, lecz kategorią obejmującą różne, odrębnie traktowane umiejętności. Każda z nich musi zostać wykupiona oddzielnie. Musisz wydać 100 PD za każdą opanowaną naukę (w nawiasie wpisujesz nazwę wyuczonej specjalności). Na przykład umiejętność nauka (teologia) jest odrębną umiejętnością niż nauka (historia).', 'brak', '100', ''],
            [15, 'Nawigacja', 'Zaawansowana', 'Inteligencja', 'Umiejętność ta wykorzystywana jest do orientowania się na lądzie i na wodzie. W zależności od wiedzy i możliwości. Bohater może nawigować według mapy albo gwiazd lub posługując się wrodzonym wyczuciem kierunku. Dzięki tej umiejętności może również ocenić długość podróży, biorąc pod uwagę topografię okolicy, porę roku i pogodę. W normalnych warunkach, utrzymanie stałego kursu wymaga jednego udanego testu umiejętności dziennie. W wyjątkowych sytuacjach Mistrz Gry może zażądać dodatkowych testów umiejętności.', 'geniusz arytmetyczny, wyczucie kierunku', '100', ''],
            [16, 'Opieka nad zwierzętami', 'Podstawowa', 'Inteligencja', 'Umiejętność ta wykorzystywana jest podczas doglądania zwierząt domowych i hodowlanych (konie, woły, świnie, psy. itd.). Codzienne czynności i karmienie zwierząt nic wymagają testu umiejętności. Może być jednak potrzebny przy próbie wykrycia objawów choroby lub zastosowania specjalnych zabiegów (na przykład zaplatanie grzywy, czesanie, przygotowanie konia do parady wojskowej, itp.).', 'brak', '100', ''],
            [17, 'Oswajanie', 'Zaawansowana', 'Ogłada', 'Wykorzystane tej umiejętności umożliwia oswajanie zwierząt. Zwierzęta domowe i hodowlane zawsze zachowują się przyjaźnie wobec Bohatera, który posiada tę umiejętność. Zwierzęta dzikie lub tresowane (na przykład psy gończe lub bojowe) mogą dać się oswoić przy udanym teście umiejętności. Mistrz Gry może przydzielić modyfikatory przy próbie oswajania zwierząt wyjątkowo agresywnych lub wyjątkowo wiernych innej osobie. Umiejętność oswajanie nie działa na potwory.', 'brak', '100', ''],
            [18, 'Otwieranie zamków', 'Zaawansowana', 'Zręczność', 'Bohater potrafi otwierać wszelkiego rodzaju zamki i kłódki. Zazwyczaj do otwarcia zamka wystarczy jeden udany test umiejętności, ale przy próbach otworzenia szczególnie skomplikowanego mechanizmu Mistrz Gry może zażądać dodatkowych testów umiejętności.', 'brak', '100', ''],
            [19, 'Plotkowanie', 'Podstawowa', 'Ogłada', 'Wykorzystanie tej umiejętności pozwala na zbieranie informacji w czasie zwykłej rozmowy. Obejmuje wymianę najświeższych nowin, plotek o ważnych osobach oraz ogólnych informacji o wydarzeniach w okolicy.', 'etykieta, łotrzyk', '100', ''],
            [20, 'Pływanie', 'Podstawowa', 'Krzepa', 'Bohater umie pływać oraz nurkować. Pływanie w spokojnej wodzie nie wymaga testu umiejętności. Test może być potrzebny przy próbie nurkowania, pływania w wartkim lub zdradliwym nurcie oraz podczas próby przepłynięcia dłuższego dystansu. W czasie pływania Szybkość Bohatera spada o połowę (zaokrąglane w górę).', 'brak', '100', ''],
            [21, 'Powożenie', 'Podstawowa', 'Krzepa', 'Bohater potrafi kierować wozem, powozem, a nawet rydwanem. Powożenie w normalnych w arunkach nie wymaga testu umiejętności. Test może być potrzebny w przypadku jazdy w trudnym terenie, z dużą prędkością lub przy wykonywaniu niebezpiecznych manewrów.', 'brak', '100', ''],
            [22, 'Przekonywanie', 'Podstawowa', 'Ogłada', 'Ta umiejętność pozwala Bohaterowi wpływać na zachowanie innych osób. Może przekonywująco kłamać, blefować. a nawet skutecznie żebrać.  Przekonywanie wykorzystuje się też podczas prób uwodzenia. W przypadku zastosowania tej umiejętności w celu nakłonienia kogoś do zrobienia czegoś niezwykłego lub niebezpiecznego. Mistrz. Gry może pozwolić nakłanianej postaci na test Siły Woli. Bohater może próbować przekonać kilka osób (jedna osoba za każde 10 punktów jego Ogłady), pod sv.u ulikiem że wszystkie te osoby rozumieją język, którym posługuje się BG.', 'etykieta, łotrzyk', '100', ''],
            [23, 'Przeszukiwanie', 'Podstawowa', 'Inteligencja', 'Ta umiejętność jest wykorzystywana przy przeszukiwaniu obszaru lub pomieszczenia, w nadziei znalezienia wskazówek, ukrytych przejść, skarbów lub pułapek. Dokładne przeszukanie pomieszczenia lub niewielkiego obszaru wymaga jednego udanego testu umiejętności.', 'brak', '100', ''],
            [24, 'Rzemiosło (różne)', 'Zaawansowana', 'różnie', 'Bohater jest fachowcem w jednej z dziedzin rzemiosła. Ta umiejętność obejmuje także te dziedziny, które formalni: nie są określone jako rzemiosło, ale wymagają posiadania wyuczonej wiedzy i odpowiednich narzędzi. Każda umiejętność 24dotyczy odrębnej dziedziny. W nawiasie podano cechę, która jest powiązana z daną umiejętnością. Najczęściej spotykanymi dziedzinami rzemiosła są: aptekarstwo (Int), bednarstwo (S). garbarstwo (S), gotowanie (Int). górnictw-o (S). handel (Ogd), jubilerstwo (Zr), kaligrafia (Zr), kamieniarstwo (Zr), kartografia (Zr), kow-alstw-o (S), krawiectwo (Zr), młynarstwo (S), piwowarstwo (Int), płatnerstwo (S), rusznikarstwo (Zr), n-marstwo (Zr), stolarstwo (Zr), szkutnictwo (Im), szewstwo (Zr), sztuka (Zr), świerarsrwo (Zr), uprawa ziemi (S), w,-rób łuków (Zr), zielarstwo (Int) oraz złotnictwo (Zr).', 'krasnołudzki fach, talent artystyczny', '100', ''],
            [25, 'Sekretne znaki (różne)', 'Zaawansowana', 'Inteligencja', 'Bohater potrafi odczytywać lub zapisywać zaszyfrowane wiadomości. Na obszarze Imperium stosuje się wiele systemów znaków. Sekretne znaki są zazwyczaj prostymi komunikatami używanymi głównie w celu ostrzeżenia, oznakowania obiektu, wskazania szlaku lub miejsca o szczególnym znaczeniu. Odczytanie lub zapisanie krótkiej, prostej wiadomości nie wymaga testu umiejętności. W przypadku bardziej skomplikowanych zapisów lub gdy fragmenty znaku są podniszczone albo zatarte. Mistrz Gry może nakazać wykonanie testu umiejętności z odpowiednimi modyfikatorami trudności. Najczęściej wykorzystywane są znaki: łowców, rycerzy zakonnych, złodziei i zwiadowców.', 'brak', '100', ''],
            [26, 'Sekretny język (różne)', 'Zaawansowana', 'Inteligencja', 'Znajomość sekretnego języka pozwala na potajemne porozumiewanie się z przedstawicielami tej samej profesji lub grupy społecznej. Sekretne języki przypominają raczej uproszczony szyfr, a nic powszechnie używane formy porozumiewania się. Wykorzystując znaki, mowę ciała i słowa kodowe wplatane w zwykłą wypowiedź, Bohater może przekazać dodatkowe znaczenie wypowiadanych słów lub większą ilość informacji w krótkim czasie. W normalnych warunkach, gdy w szyscy rozmawiający znają dany sekretny język, test umiejętności nie jest potrzebny, aczkolwiek może być wymagany w niesprzyjających wirunkach (na przykład na głośnej ulicy lub w czasie bitwy). Najczęściej używane sekretne języki to: bitewny, łowców i złodziejski.', 'brak', '100', ''],
            [27, 'Skradanie się', 'Podstawowa', 'Zręczność', 'Umiejętność ta umożliwia Bohaterowi ciche poruszanie się w prawie każdym terenie. Skradając się, Bohater może wykonywać najwyżej jedną akcję „ruch" w rundzie. Test skradania się jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika.', 'grotołaz, ulicznik, wędrowiec', '100', ''],
            [28, 'Splatanie magii', 'Zaawansowana', 'Siła Woli', 'Wykorzystanie tej umiejętności ułatwia Bohaterowi kontrolowanie Wiatrów Magii. Każde rzucenie zaklęcia wymaga manipulacji Wiatrami Magii, jednak splatanie magn wykorzystuje się wtedy, gdy wymagana jest większa kontro a md czarem lub jego precyzyjne przygotowanie. Szczegółowe zesady dotyczące rzucania zaklęć i umiejętności splatania magii znajdziesz w Rozdziale VII: Magia.', 'zmysł magii', '100', ''],
            [29, 'Spostrzegawczość', 'Podstawowa', 'Inteligencja', 'Bohater Gracza, który posiada tę umiejętność, dokładniej obserwuje otoczenie, często zauważając szczegóły przeoczone przez innych. Dzięki temu ma większe szanse na zauważenie pułapki, zapadni łub ukrytego przejścia. Spostrzegawczość jest używana głównie do ustalania tego co Bohater widzi, choć obejmuje także pozostałe zmysły. Może więc być użyta do określania doznań smakowych, zapachowych, słuchowych i dotykowych. Spostrzegawczość bywa często stosowana w przeciwstawnych testach umiejętności, szczególnie przeciwko takim umiejętnościom jak charakteryzacja, skradanie się i ukrywanie się. Udany test umiejętności pozwala Bohaterowi na określenie liczebności, odległości, wielkości obserwowanego obiektu, itp. Nieudany test może oznaczać uzyskanie niedokładnych informacji.', 'bystry wzrok, czuły słuch, geniusz arytmetyczny', '100', ''],
            [30, 'Sztuka przetrwania', 'Podstawowa', 'Inteligencja', 'Umiejętność ta może zapewnić przeżycie w dziczy. Obejmuje znajomość technik łowienia ryb, polowania, oprawiania zwierzyny, rozpalania ognia, znajdowania pożywienia, konstruowania szałasów, itp.', 'brak', '100', ''],
            [31, 'Śledzenie', 'Zaawansowana', 'Zręczność', 'Wykorzystując tę umiejętność, bohater może podążać za kimś, samemu pozostając niezauważonym. Test śledzenia jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika.', 'brak', '100', ''],
            [32, 'Targowanie', 'Podstawowa', 'Ogłada', 'Umiejętność ta umożliwia negocjowanie cen towarów i usług. W przypadku towarów codziennego użytku wystarczy zwykły test umiejętności. Jeśli Bohater targuje się o cenny przedmiot (na przykład próbuje ustalić koszt wyjątkowo cennego rękopisu), Mistrz Gry może zarządzić przeciwstawny test targowania (z ewentualnymi modyfikatorami trudności).', 'żyłka handlowa', '100', ''],
            [33, 'Torturowanie', 'Zaawansowana', 'Ogłada;Krzepa', 'Dzięki zastosowaniu rozmaitych działań i środków przymusu Bohater potrafi wydobyć interesujące go informacje od osoby niechętnej do współpracy. Umiejętność obejmuje zarówno psychiczne (Ogd) znęcanie się, jak i fizyczne tortury (K). Ofiara może opierać się torturom, wykonując odpowiednio test (SW) lub (Odp).', 'groźny', '100', ''],
            [34, 'Tresura', 'Zaawansowana', 'Ogłada', 'Bohater potrafi uczyć zwierzęta wykonywania różnych sztuczek i słuchania prostych poleceń. Zwykle tresurze poddajc się psy, konie i sokoły, choć Mistrz Gry może pozwolić na tresowanie bardziej niezwykłych zwierząt. Wyuczenie zwierzęcia zajmuje sporo czasu. Test umiejętności należy wykonywać raz na tydzień tresury. Nauczenie prostej sztuczki wymaga pojedynczego udanego testu, średnio trudna sztuczka wymaga trzech udanych testów umiejętności, natomiast bardzo trudna - dziesięciu udanych testów umiejętności.', 'brak', '100', ''],
            [35, 'Tropienie', 'Zaawansowana', 'Inteligencja', 'Bohater potrafi wyszukiwać ślady zwierząt, a także ludzi i innych stworzeń. Podążanie wyraźnym tropem nie wymaga testu umiejętności i nic spowalnia tempa poruszania się. Test umiejętności może być jednak potrzebny w trudnych warunkach terenu lub pogody. Odpowiedni poziom skuteczności może dostarczyć dodatkowych informacji (o liczebności grupy, odległości od tropionego stworzenia, a nawet jege cechach osobniczych).', 'brak', '100', ''],
            [36, 'Ukrywanie się', 'Podstawowa', 'Zręczność', 'Wykorzystanie tej umiejętności umożliwia Bohaterowi ukrywanie się w niemal dowolnym terenie, pod warunkiem, że istnieje realna szansa schowania się za jakimś obiektem (mur, drzewo, budynek, itp.). Przy próbie ukrycia się na otwartej, pustej przestrzeni (na przykład na środku ulicy) test umiejętności automatycznie jest nieudany. Ukrywanie się bywa często wykorzystywane przeciwko testowi spostrzegawczości przeciwnika.', 'grotołaz, ulicznik, wędrowiec', '100', ''],
            [37, 'Unik', 'Zaawansowana', 'Zręczność', 'Wykorzystarie tej umiejętności umożliwia Bohaterowi uniknięcie autku podczas walki wręcz. Unik można stosować najwyżej raz na rundę. Szczegółowe zasady unikania ciosów znajdziesz v Rozdziale VI: Walka, obrażenia i ruch.', 'brak', '100', ''],
            [38, 'Warzenie trucizn', 'Zaawansowana', 'Inteligencja', 'Bohater potrafi przyrządzać rozmaite trucizny pochodzenia zwicrzęcegc lub roślinnego, a także trucizny uzyskiwane alchemiczni;. Szczegółowy opis trucizn i efektów ich działania znajdziesz w Rozdziale V: Ekwipunek.', 'brak', '100', ''],
            [39, 'Wiedza (różne)', 'Zaawansowana', 'Inteligencja', 'Umiejętność ta zapewnia wiedzę o zwyczajach, strukturze władzy, najważniejszych dostojnikach, obyczajach ludowych oraz przesądach mieszkańców danej krainy, członków danej grupy społecznej lub przedstawicieli danej rasy. Wiedza nic jest równoznaczna ze studiami naukowymi (to oddaje umiejętność nauka), lecz zapewnia jedynie podstawowe informacje, jakie Bohater zdobył w czasie podróży po świecie. Podobnie jak w przypadku umiejętności nauka, wiedza to szersza kategoria obejmująca różne, oddzielnie zdobywane konkretne umiejętność. Najczęściej wiedza dotyczy: Bretonii, Estalii, Imperium. Jałowej Krainy, Kisleva, Księstw Granicznych, Norski, Tilei oraz elfów, krasnoludów, niziołków i ogrów.', 'obieżyświat', '100', ''],
            [40, 'Wioślarstwo', 'Podstawowa', 'Krzepa', 'Bohater potrafi sterować tratwami, barkami i innymi łodziami wiosłowymi. Utrzymanie kursu w normalrych warunkach i proste manewry nie wymagają testu umiejętności. Mistrz Gry może uznać za stosowne wykonanie testu umiejętności w przypadku kiepskiej pogody, wysokiej fali, pokonywania progów rzecznych lub omijania mielizn.', 'brak', '100', ''],
            [41, 'Wspinaczka', 'Podstawowa', 'Krzepa', 'Twój Bohater potrafi wspinać się na drzewa, mury, ska nc ściany i inne pionowe przeszkody. W normalnych warunkach test umiejętności wykonuje się raz na rundę Wspinanie się w czasie walki wymaga poświęcenia akcji podwójnej. Udany test oznacza, że Bohater wspiął się na wysokość równą połowie jego Szybkości (zaokrąglane w górę), mierzoną w metrach.', 'brak', '100', ''],
            [42, 'Wycena', 'Podstawowa', 'Inteligencja', 'Bohater potrafi szacować wartość rzeczy codziennego użytku, jak również przedmiotów wartościowych, takich jak biżuteria, klejnoty i dzieła sztuki. Udany test umiejętności pozwala określić rynkową wartość przedmiotu. Ponieważ nieudany test umiejętności może spowodować błędne oszacowanie wartości przedmiotu. Mistrz Gry powinien wykonać rzut w tajemnicy i zależnie od wyniku poinformować gracza o ustalonej w ten sposób wartości przedmiotu.', 'talent artystyczny, żyłka handlowa', '100', ''],
            [43, 'Wykrywanie magii', 'Zaawansowana', 'Siła Woli', 'Umiejętność ta umożliwia Bohaterowi wykrywanie subtelnych zawirowań, jakie towarzyszą magicznej jurze. Czarodzieje opisują to jako szósty, siódmy i ósmy zmysł człowieka. Wśród chłopstwa to zjawisko znane jest pod nazwą „wiedźm i wzrok”. Udany test umiejętności pozwala określić, czy przedmiot, postać lub obszar poz.ostaje pod wpływem czaru. Wykorzystując tę umiejętność, cz.a-odziej może ustalić siłę Wiatrów Magii w najbliższej okolicy. Dodatkowe informacje na ten temat znajdziesz w Rozdziale VII: Magia.', 'zmysł magii', '100', ''],
            [44, 'Zastawianie pułapek', 'Zaawansowana', 'Zręczność', 'Bohater potrafi konstruować różnego rodzaju pułapki na zwierzęta. W Imperium używa się pułapek unieruchamiijących. jak też uśmiercających złapane zwierzę. Za każdą założoną pułapkę wykonuje się jeden test umiejętności na dzień. Udany test oznacza, że w pułapkę złapało się zwierzę.', 'brak', '100', ''],
            [45, 'Zastraszanie', 'Podstawowa', 'Krzepa', 'Dzięki tej umiejętności Bohater może zastraszać lub zmuszać do uległości inne osoby. Ofiary, które nic chcą ugiąć się przed groźbami, mogą wykonać test Siły Woli. Reakcja postaci zależy całkowicie od decyzji Mistrza Gry, k:óry bierze pod uwagę jej osobowość oraz wynik testu zastraszania. W niektórych sytuacjach (szantaż, itp.). Mistrz Gry może uznać, że bardziej odpowiednią cechą do testu zastraszania może być Ogłada', 'groźny', '100', ''],
            [46, 'Znajomość języka (różne)', 'Zaawansowana', 'Inteligencja', 'Ta umiejętność umożliwia Bohaterowi porozumiewanie się w obcym języku. Większość języków Starego Świata wywodzi się ze wspólnego starożytnego narzecza, choć w ciągu wielu wieków różnice między poszczególnymi dialektami doprowadziły do powstania odrębnych języków. W normalnych warunkach, gdy wszyscy rozmawiający znają dany język, test umiejętności nie jest potrzebny. Test umiejętności może być potrzebny w przypadku prób naśladowania regionalnych akcentów lub gdy Bohater Gracza próbuje przekonać słuchających, że język obcy jest ojczystym jego językiem. Najczęściej używanymi językami są: bretoński (Bretonia), eltharin (elfi), estalijski (Estalia), khazalid (krasnoludzki), kislevski (Kislev), norski (Norska), tileański (Tilea) oraz Reikspiel czyli staroświatowy (Imperium) i nieco podobny do niego język niziołków. Uczeni posługują się także językiem klasycznym, choć obecnie występuje on głównie w formie pisanej. Mniej cywilizowane rasy posługują się językiem goblińskim (orki, gobliny i hobgobliny), narzeczem grumbarth (ogry) oraz mroczną mową (zwierzoludzie i inne istoty Chaosu).', 'naśladowca, obieżyświat, poliglota', '100', ''],
            [47, 'Zwinne palce', 'Zaawansowana', 'Zręczność', 'Dzięki tej użytecznej umiejętności Bohater potrafi ukryć w dłoni małe przedmioty lub wykonywać sztuczki z kartami i monetami. Zwinne palce przydają się również przy ukradkowym sięganiu do cudzych sakiewek. Test zwinnych palców jest często wykonywany w przeciwstawnym teście umiejętności przeciwko spostrzegawczości przeciwnika.', 'brak', '100', ''],
            [48, 'Żeglarstwo', 'Zaawansowana', 'Zręczność', 'Dzięki tej umiejętności Bohater potrafi sterować statkami żaglowymi. Dodatkowo Bohater dysponuje wiedzą o budowie okrętów, różnych rodzajach żagli, a także umiejętnością przewidywania pogody na morzu. Żeglowanie po spokojnych wodach nie wymaga testu umiejętności. Trudne warunki pogodowe, wysokie fale lub wykonywanie manewrów w czasie bitwy mogą wymagać testu umiejętności o odpowiednim stopniu trudności.', 'brak', '100', ''],
            [49, 'Refleks walki', 'Zaawansowana', 'Walka Wręcz', 'Normalnie wszystkie ataki bohatera w rundzie muszą być skierowane przeciwko jednemu celowi. Bohater z tą umiejętnością może zignorować ten przepis i atakować więcej niż jednego przeciwnika (jeśli pozostały mu jakieś ataki w rundzie)', '', '250', 'WW:40&A:2'],
            [50, 'Błyskawiczne uderzenie', 'Zaawansowana', 'Zręczność', 'Ta umiejętność pozwala na wyjęcie broni i uderzenie w tym samym momencie, to znaczy bez modyfikacji I lub zmniejszenia ataków', '', '250', 'Zr:40'],
            [51, 'Śmiercionośny atak', 'Zaawansowana', 'Walka Wręcz', 'Normalnie atak bez użycia broni będzie przeprowadzany z modyfikatorem -20 WW oraz -3 do obrażeń. Bohater posiadający umiejętność Śmiercionośny atak będzie mógł użyć swoich rąk i nóg bez ujemnych modyfikatorów do WW i obrażeń.', '', '250', 'Bijatyka, Zapasy lub inna umiejętność walki bez broni'],
            [52, 'Szczegółowa wiedza', 'Zaawansowana', 'Inteligencja', 'Ta umiejętność pozwala na dokładne poznanie pewnego zagadnienia. Bohater będzie w stanie odpowiedzieć na dowolne proste pytanie dotyczące jego wiedzy automatycznie, ale będzie potrzebował testu inteligencji aby odpowiedzieć na trudniejsze lub bardziej szczegółowe pytania.. 1 Co może stać się przedmiotem nauki zależy wyłącznie od MG i logiki gry. Np. poznanie Wiedzy o Demonologii będzie wymagało dostępu do bibliotek cechu magów i nie pozwoli na naukę i rzucanie czarów demonologicznych. Przykładowo wiedza może obejmować takie dziedziny jak: Wiedza o historii Gnomów, Zasady działania mechanizmów pułapek (daje bonus do rozbrajania pułapek +10 jeżeli postać ma taką umiejętność) lub Wiedza o geografii Imperium', '', '250|rok studiów', 'czytanie i pisanie|ewentualnie coś dodatkowego'],
            [53, 'Mistrzostwo w broni', 'Zaawansowana', 'Walka Wręcz|Umiejętności Strzeleckie', 'Lata treningu dają bohaterowi w posługiwaniu się określonym rodzajem broni premię +10 do WW/US. Broń może należeć do dowolnego typu (czas poświęcony na znalezienie nauczyciela zależy od jej popularności).Umiejętność można nabywać wielokrotnie, ale dla różnych rodzajów broni. Jeśli broń należy do broni specjalnych wtedy koszt umiejętności wynosi raczej 500 PD a nie 250.', '', '250|500', 'WW:40|US:40&nie uczonego'],
            [54, 'Morderczy cios', 'Zaawansowana', 'Walka Wręcz', 'Bohater wykorzystujący morderczy cios atakuje w czasie rundy raz (mimo większej liczby ataków), zadając podczas tego ataku większe obrażenia. Gracz musi zadeklarować użycie umiejętności na początku rundy, przed podjęciem jakichkolwiek działań. Bohater atakujący w ten sposób zyskuje modyfikator +10 do WW jeżeli postać miała ponad 3 ataki. Obrażenia są równe Sile + modyfikatory z broni oraz magii + 2k6. Dodatkowe obrażenia zadawane są normalnie, z tą różnicą że możliwe jest zadanie podwójnych dodatkowych obrażeń. Przykład: Martinez - Zabójca Gigantów uderza przy pomocy morderczego ciosu goblina. Trafia i rzuca na obrażenia 12 ( 2 razy 6 ! ), sprawdza czy zadał dodatkowe obrażenia ( jeden rzut ) i udało się. Rzuca jeszcze raz na obrażenia ( 2k6) i wyszło 11 ( 5 i 6 ) .Zadał więc jeszcze raz dodatkowe obrażenia, ale już tylko pojedyncze, rzuca więc k6 i zwiększa obrażenia o 4. Goblin jest zdecydowanie martwy', '', '300', 'WW:40&A:3&SW40'],
            [55, 'Rymotwórstwo', 'Zaawansowana', 'Ogłada', 'Rymotwórstwo pozwala na poczekaniu wymyślać zabawne wierszyki ( test INT +30 ), lub układać w czasie rzeczywistym poważne utwory ( test INT ) .Pozwala to na wygłoszenie lub zaśpiewanie na poczekaniu ballady o wielkości rasy krasnoludów ( jeżeli mają właśnie zamiar cię zgładzić ). Osoba wygłaszająca poemat jest traktowana jakby miała wyższą o jeden klasę społeczną i dostaje bonus +20 do OGD. Jeżeli test inteligencji przy wypowiedzi się nie powiedzie skutki są dokładnie odwrotne. Należy pamiętać że pospólstwo woli raczej proste i pieprzne wierszyki a wyższe sfery ballady i poematy ( umiejętność pozwala je również lepiej zapamiętać i wydeklamować bez pomyłki )', '', '250', 'Ogd:40&gadanina lub inna'],
            [56, 'Stalowe nerwy', 'Zaawansowana', 'Siła Woli', 'Niektóre z postaci są w stanie nauczyć się walczyć ze strachem i nie ulegać mu. Potrzebne jest do tego duże opanowanie i pewna wiedza pozwalająca racjonalnie wyjaśniać pewne rzeczy lub uważać je za normalny element świata. Bohater posiadający Stalowe nerwy może negować efekt strachu (bez względu na wynik testu) oraz efekty grozy ( test +20 do OP ). Nieudany test strachu mimo iż nie ma bezpośredniego wpływu na postać, powoduje otrzymywanie przez nią punktów obłędu. Stalowe nerwy mogą być wykorzystane także w każdej stresowej sytuacji wymagającej testu OP. Przykład: Clem Sherwood próbuje otworzyć zamek w drzwiach do skarbca. Słyszy na schodach kroki strażników. MG zarządza test OP. OP Clema wynosi 42, a wynik rzutu to 54, więc Clem będzie miał ujemny modyfikator przy próbie otwarcia zamka. Jeżeli Clem miałby Stalowe nerwy, test byłby udany i nie byłoby ujemnego bonusu przy otwieraniu zamka.', '', '250', 'SW:40&bg MA SKOMPLETOWANA PROFESJE UCZONEGO'],
            [57, 'Parada', 'Zaawansowana', 'Zręczność', 'Parada pozwala na wycofanie się w czasie walki do tyłu, niwelując możliwość zostania trafionym przez przeciwnika, przez odbicie jego broni i odejście w tył z równoczesnym wykonaniem uniku. Wykonanie parady uniemożliwia wykonanie jakichkolwiek ataków w rundzie jeżeli bohater ma dwa ataki, lecz nadwyżkę ataków przeprowadza się w normalny sposób. Aby wykonać paradę, należy na początku rundy zadeklarować że chce się ją wykonać i po ilu atakach (jeżeli istnieje nadwyżka). Wykonujący paradę rzuca na WW i jeżeli test jest udany parada została wykonana. Należy dodatkowo sprawdzić czy wykonujący paradę ma większą inicjatywę od przeciwnika. Jeżeli tak, parada jest wykonana i żaden cios przeciwnika nie trafi bohatera. Jeżeli jest niższa należy przeprowadzić test Inicjatywy ( szansa szybszego zadziałania jest równa 50% + I bohatera - I przeciwnika ). Test I jest wykonywany przy aktualnej I, więc jakiekolwiek wykonane ataki ją obniżają. Spalenie któregokolwiek z testów oznacza stratę 2 ataków, uników i -10 do WW w tej rundzie. Parada może być wykonana jeżeli walczy się z jednym przeciwnikiem i ma się miejsce na odejście.', '', '300', 'Zr:40&WW:40&A:3'],
            [58, 'Szeroka parada', 'Zaawansowana', '', 'Szeroka parada jest analogiczna do parady z tym że może być wykonana przeciwko maksymalnie trzem przeciwnikom atakującym z przodu. Przy szerokiej paradzie nie można atakować, a w przypadku testu I, testuje się I najszybszego przeciwnika.', '', '600', 'Zr:50&WW:50&A:3'],
            [59, 'Zniszczenie', 'Zaawansowana', '', 'Przy pomocy zniszczenia, gracz może uszkodzić każdą rzecz w sposób trwały, szybki i nie dający dużych szans na jej naprawienie. Niszcząc daną rzecz, postać musi posiadać przedmioty umożliwiające jej uszkodzenie ( Zniszczenie miecza wymaga dużo więcej narzędzi niż uszkodzenie pistoletu ). Postać jest w stanie uszkodzić nawet rzeczy o których działaniu nie ma zielonego pojęcia ( test INT ) - ale zniszczenie katapulty nie będzie wymagało tego testu, gdyż każdy zna ogólne zasady ich działania. Przykład: Clem Sherwood bawi się monetą i pistoletem pojedynkowym swego ojca. Prawdopodobnie Clem zostanie sierotą, ponieważ przy następnym pojedynku pistolet rozleci się jego ojcu w dłoniach na k10+2 elementy.', '', '200', 'Miesiąc przebywania wśród gnomów'],
            [60, 'Podpis', 'Zaawansowana', '', 'Jeżeli Zabójca Gigantów lub inny przedstawiciel inteligencji pracującej zapragnie nauczyć się podpisywać, nie znając alfabetu, umożliwia mu to umiejętność Podpis. Postać mająca tą zdolność, może, po paru minutach sapania nad kartką papieru, wykaligrafować swoje imię. Bohater nie potrafi odczytać absolutnie nic ani nic innego napisać ponieważ to co pisze jest dla niego kopiowaniem z pamięci bardzo skomplikowanego rysunku. Wykonanie napisu wymaga testu podwojonej INT. Można nauczyć się pisowni dowolnego zdania, ale każdy dodatkowy wyraz kosztuje 10 PD. Nauka tej umiejętności wymaga testu podwojonej inteligencji. Przykład: Gotrek - Z.G. wydaje 30 PD. Udany test inteligencji ( INT Gotreka = 35, rzucił 70 czyli oczko ), więc nauczył się pisowni trzech wyrazów. W czasie następnej wizyty w karczmie Gotrek pijąc piwo z zapałem dłubie nożem w stole ( udany test podwojonej INT ). Po jego wyjściu podchodzący do stołu barman widzi napis: "TU BYŁEM - GOTREK"', '', '10', 'Specjalne'],
            [61, 'Berserker ', 'Zaawansowana', '', 'ta umiejętność pozwala bohaterowi na wpadniecie w morderczy szal,otrzymuje modyfikator +20 do walki wręcz,natomiast wszyscy jego wrogowie musza wykonać test na opanowanie, jeżeli sie nie powiedzie uciekną w popłochu, co 3 rundy MG powinien wykonać po kryjomu test ryzyka czy bohater nie podda sie berserkerowi i nie zacznie atakować swoich towarzyszy, szał trwa k12 rund i może być używany 2 razy dziennie', '', '350', 'WW:50&ZR:50&SW:40'],
            [62, 'Specjalny atak', 'Zaawansowana', '', 'Możliwość wykonywania ataków specjalnych (combos)', '', '150', ''],
            [63, 'Zamaszyste cięcie', 'Zaawansowana', '', 'Pozwala na trafienie kilku przeciwników naraz. Wymagany jest rzut ataku dla każdego z nich przy -10 do WW. Ta opcja zajmuje tyle ataków ile przeciwników ma zostać trafionych', '', '200', ''],
            [64, 'Podwójne uderzenie', 'Zaawansowana', '', 'Wojownik uczy się walczyć bronią w każdej ręce, bo czyż dwie bronie nie są lepsze niż jedna? Młody wojownik uczy się korzystać z obu rąk, wymierzając równocześnie ciosy w różne cele. W miarę rozwoju tego talentu atakuje z coraz większą celnością i opanowaniem. Efekt: osoba trzymająca dwie bronie mogą to być tylko jednoręczne może zadać atak tymi brońmi bez rzadnych modyfikatorów może zadać dwóm różnym przeciwnikom z modyfikatorem +1Obr. dla każdego celu lub temu samemu. Można tą umiejętność wykorzystać raz w rundzie.', '', '200', '']
        ];
    }

    private function getWfrpTalents()
    {
        return [
            [1, 'Artylerzysta', 'Bohater został świetnie wyszkolony w obsłudze broni palnej. Dzięki tej zdolności może przeładować broń palną w czasie krótszym o akcję. Jeśli Bohater posiada również zdolność błyskawiczne przeładowanie, może korzystać naraz z obu zdolności (skracając czas przeładowania broni palnej o akcję podwójną).', 'Ładowanie broni palnej krótsze o 1 akcję', '', ''],
            [2, 'Artysta', 'Bohater jest wyjątkowo uzdolniony, tworzący dzieła sztuki (np. malarz, rzeźbiarz), kreujący jakąś rolę (aktor) lub wykonujący własne utwory muzyczne (np. kompozytor, pieśniarz). Otrzymuje modyfikator +10 do testów kuglarstwa (aktorstwo, śpiew) albo rzemiosła (sztuka).', '10 do kuglarstwa (aktorstwo, śpiew) albo rzemiosła (sztuka)', '', ''],
            [3, 'Bardzo silny', 'Bohater obdarzony jest wyjątkową siłą. Otrzymuje +5 do Krzepy, dodawane do początkowej wartości cechy. Może to zmienić wartość Siły Bohatera, zgodnie z zasadami opisanymi na str. 19.', 'Krzepa +5 na stałe', '5', '3'],
            [4, 'Bardzo szybki', 'Bohater potrafi poruszać się znacznie szybciej niż inni. Otrzymuje + 1 do Szybkości, dodawane do początkowej wartości cechy.', 'Szybkość +1 na stałe', '1', '13'],
            [5, 'Bijatyka', 'Bohater nauczył się walczyć w karczemnych burdach i miejskich rozróbach. Otrzymuje modyfikator +10 do Walki Wręcz podczas ataku bez broni. Dodatkowo otrzymuje modyfikator +1 do obrażeń zadawanych podczas takiego ataku.', 'Walka bez broni: WW+10, obrażenia +1', '', ''],
            [6, 'Błyskawiczne przeładowanie', 'Bohater jest doświadczonym strzelcem. Dzięki tej zdolności może przeładować broń strzelecką w czasie krótszym o akcję. Bohater używający błyskawicznego przeładowania może napiąć kuszę w czasie jednej akcji zwykłej, podczas gdy normalnie wymaga to akcji podwójnej. Jeśli przeładowanie broni normalnie zajmuje akcję, korzystając z tej zdolności można to wykonać w ramach akcji natychmiastowej. Dzięki temu Bohater może przeładować taką broń praktycznie w mgnieniu oka, co pozwala na wykonanie „ataku wielokrotnego" z broni strzeleckiej. Szczegółowe zasady wykonywania „ataku wielokrotnego’ znajdziesz w Rozdziale VI: Walka, obrażenia i ruch.', 'Skraca przeładowanie broni strzeleckiej o 1 akcję', '', ''],
            [7, 'Błyskawiczny blok', 'Bohater, który wykonuje „atak wielokrotny” (więcej na ten temat w Rozdziale VI: Walka, obrażenia i ruch), może poświęcić jeden z ataków, otrzymując w zamian możliwość sparowania ataku przeciwnika. Na przykład Bohater mający 3 Ataki i deklarujący atak wielokrotny, mógłby wykonać dwa ataki i raz sparować atak przeciwnika. Bohater nadal może parować najwyżej jeden atak na rundę.', '1 parowanie w ataku wielokrotnym', '', ''],
            [8, 'Błyskotliwość', 'Bohater obdarzony jest wyjątkową inteligencją. Otrzymuje + 5 do Inteligencji, dodawane do początkowej wartości cechy.', 'Inteligencja +5 na stałe', '5', '6'],
            [9, 'Brawura', 'Obdarzony tą zdolnością Bohater wykazuje się wyjątkową śmiałością i ruchliwością w walce. Może wykonać akcję „skok” poświęcając na to akcję zwykłą (zamiast akcji podwójnej). Zdolność zwiększa też maksymalny zasięg wszystkich skoków o 1 metr.', 'Skok jako akcja pojedyncza, zasięg skoku +1 m', '', ''],
            [10, 'Broń naturalna', 'Postać dysponuje ostrymi kiami lub pazurami, których z powodzeniem może używać w walce. W czasie walki bez broni jest traktowana, jak gdyby używała broni jednoręcznej. Broń naturalna nie pozwala na parowanie ciosów. W przypadku broni naturalnej nic można stosować rozbrajania.', 'Szpony, kły itp., działają jak broń ręczna', '', ''],
            [11, 'Broń specjalna (różne)', 'Bohater potrafi władać bronią, która wymaga specjalistycznego treningu. Każda zdolność broń specjalna jest odrębną zdolnością. Na przykład broń specjalna (dwuręczna) różni się od zdolności broń specjalna (rzucana). Każda zdolność musi zostać wykupiona oddzielnie. Najczęściej spotykanymi rodzajami broni specjalnych są: dwuręczna, kawaleryjska, mechaniczna, palna, parująca, rzucana, szermiercza, unieruchamiająca oraz korbacze, kusze, luki i proce. Szczegółowy opis poszczególnych rodzajów broni znajdziesz w Rozdziale V: Ekwipunek.', '', '', ''],
            [12, 'Bystry wzrok', 'Bohater obdarzony jest doskonałym wzrokiem. Otrzymuje modyfikator +10 do testów spostrzegawczości podczas rozglądania się oraz do testów czytania z warg.', '+10 do testów opartych na wzroku', '', ''],
            [13, 'Charyzmatyczny', 'Bohater obdarzony jest zniewalającym urokiem osobistym. Otrzymuje +5 do Ogłady, dodawane do początkowej wartości cechy.', 'Ogłada +5 na stałe', '5', '8'],
            [14, 'Chirurgia', 'Bohater poznał tajniki najnowszej wiedzy medycznej. Otrzymuje modyfikator +10 do testów leczenia. W przypadku leczenia ciężko rannego pacjenta udany test przywraca 2 punkty Żywotności zamiast, jak normalnie, tylko 1. Jeśli w wyniku trafienia krytycznego istnieje ryzyko utraty kończyny, pacjent leczony przez chirurga otrzymuje modyfikator +20 do Odporności podczas testów związanych z ryzykiem utraty kończyny. Szczegółowe zasady dotyczące trafień krytycznych znajdziesz w Rozdziale VI: Walka, obrażenia i ruch.', '+10 do testów leczenia', '', ''],
            [15, 'Chodu!', 'W chwili zagrożenia Bohater odkrywa w sobie zadziwiające możliwości fizyczne. Uciekając z pola walki lub z miejsca zagrożenia, na 1k10 rund otrzymuje +1 do Szybkości.', 'Sz +1 na k10 rund podczas ucieczek', '', ''],
            [16, 'Czarnoksięstwo', 'Bohater poznał sekret Czarnej Magii Dhar i potrafi jej używać do wspomożenia siły swoich zaklęć. Korzystanie z czamoksięstwa umożliwia zdobycie większej mocy, ale jest także bardziej ryzykowne, ża każdym razem, gdy Bohater rzuca czar może wykorzystać energię Dhar do jego wzmocnienia. Wykonując rzut na poziom mocy czaru, możesz rzucić dodatkową kostką k10 i zignorować najmniejszy z uzyskanych wyników, który jednak liczy się przy sprawdzaniu Przekleństwa Tzeentcha. Na przykład czarodziej z Magią 2, który rzuca zaklęcie z wykorzystaniem czamoksięstwa, rzuca 3k10 i wybiera dwa najwyższe wyniki. Wszystkie trzy kostki są używane do sprawdzania Przekleństwa Tzcentcha. Gdyby na kostkach wypadło 6, 6 i 6, poziom mocy czaru wyniósłby 12 (6 + 6), jednak czar wywołałby Poważną Manifestację Chaosu. Znajomość czamoksięstwa jest wymagana przy rzucaniu czarów z magii czarnoksięskiej. Szczegółowe zasady rzucania zaklęć znajdziesz w Rozdziale VII: Magia.', '+1k10 do testu mocy zaklęcia; większa szansa na Przekleństwo Tzeentcha', '', ''],
            [17, 'Człowiek-guma', 'Bohater potrafi wyginać swojo ciało w sposób nieosiągalny dla zwykłych osób. Otrzymuje modyfikator +10 do testów kuglarstwa (akrobatyka) oraz modyfikator +20 do Zręczności podczas testów wyzwalania się z więzów, przeciskania przez szczeliny, itp.', '+20 do wyzwalania się z więzów, kuglarstwo(akrobatyka) +10', '', ''],
            [18, 'Czuły słuch', 'Bohater obdarzony jest wyjątkowo czułym słuchem. Otrzymuje modyfikator +20 do testów spostrzegawczości podczas nasłuchiwania.', '+20 do testów opartych na słuchu', '', ''],
            [19, 'Dotyk mocy', 'Niektóre czary używane w walce wymagają dotknięcia przeciwnika. Bohater, który posiada zdolność dotyk mocy, otrzymuje modyfikator +20 do Walki Wręcz przy testach związanych z rzucaniem czarów dotykowych.', '+20 do WW podczas zaklęć dotykowych', '', ''],
            [20, 'Etykieta', 'Bohater potrafi odpowiednio zachowywać się we wszelkich sytuacjach towarzyskich. Otrzymuje modyfikator +10 do testów plotkowania i przekonywania podczas rozmów z przedstawicielami szlachty i arystokracji. Modyfikator stosuje się również w sytuacjach, gdy wymagana jest znajomość etykiety (na przykład podszywanie się pod szlachcica z wykorzystaniem charakteryzacji).', '+10 do testów związanych z Arystokracją', '', ''],
            [21, 'Geniusz arytmetyczny', 'Bohater potrafi błyskawicznie rachować w umyśle oraz, mając do dyspozycji dostatecznie dużo czasu, może rozwiązać niemal dowolny problem matematyczny. Otrzymuje modyfikator +10 do testów hazardu i nawigacji oraz modyfikator +20 do testów spostrzegawczości związanych z oceną odległości, ciężaru, itd.', '+10 do hazardu i nawigacji; +20 do szacowania odległości, wagi itp.', '', ''],
            [22, 'Grotołaz', 'Bohater wychował się w jaskiniach bądź często po nich wędrował. Bez trudu potrafi poruszać się w podziemiach. Otrzymuje modyfikator +10 do testów skradania się i ukrywania się wykonywanych pod powierzchnią ziemi lub w jaskiniach.', '+10 do skradania i ukrywania pod ziemią i w jaskiniach', '', ''],
            [23, 'Groźny', 'Wygląd, wzrost lub zachowanie Bohatera wzbudzają respekt i instynktowny niepokój wśród obserwatorów\'. Otrzymuje modyfikator +10 do testów zastraszania i torturowania.', '+10 do zastraszania i torturowania', '', ''],
            [24, 'Gusła', 'Bohater odkrył w sobie dziki talent magiczny, który udoskonala metodą prób i błędów, nie mając dostępu do magicznych studiów. Bohater potrafi rzucać czary magii prostej (gusła) bez konieczności posiadania umiejętności język tajemny. Do rzucania czarów nadal wymagana jest zdolność magia prosta (gusła). Za każdym razem, gdy Bohater korzysta z zaklęć magii prostej (gusła), musisz rzucić dodatkową kostką k10. Wynik rzutu nie dodaje się do poziomu mocy czaru, lecz jest używany do sprawdzania Przekleństwa Tzeentcha. Jeśli Twój BG nauczy się umiejętności język tajemny, nie będziesz musiał rzucać dodatkową kostką.', 'Dodatkowa kość przy określaniu poziomu mocy; służy do sprawdzenia przekleństwa Tzeentcha', '', ''],
            [25, 'Intrygant', 'Bohater jest mistrzem rozgrywek politycznych i intryg. Otrzymuje modyfikator +10 do testów przekonywania związanych z intrygami oraz do Siły Woli podczas testów przeciwko przekonywaniu ze strony innych osób.', '+10 do przekonywania i testów SW przeciwko przekonywaniu związanych z intrygami', '', ''],
            [26, 'Krasnoludzki fach', 'Krasnoludy są urodzonymi rzemieślnikami. Bohater otrzymuje modyfikator +10 do testów rzemiosła: górnictwo, kamieniarstwo, kowalstwo, jubilerstwo, piwowarstwo, płatnerstwo i rusznikarstwo.', '+10 do rzemiosła(górnictwo, kamieniarstwo, kowalstwo, jubilerstwo, piwowarstwo, płatnerstwo i rusznikarstwo)', '', ''],
            [27, 'Krasomówstwo', 'Bohater potrafi przemawiać tak pięknie i przekonywująco, że może poderwać do działania całe tłumy.', 'Przekonywanie na grupę osób 100 razy liczniejszą niż normalnie; wymaga Przemawiania', '', ''],
            [28, 'Krzepki', 'Bohater, który posiada tę zdolność, w czasie wielu przygód nabrał niesamowitej krzepy. Może nosić ciężki pancerz lub zbroję płytową bez zmniejszenia Szybkości. Szczegółowy opis pancerzy znajdziesz w Rozdziale V: Ekwipunek.', 'BG nosi ciężki pancerz i zbroję płytową bez kar', '', ''],
            [29, 'Latanie', 'Postać potrafi latać. Zasady dotyczące latania znajdziesz w Rozdziale VI: Walka, obrażenia i ruch.', 'Postać potrafi latać', '', ''],
            [30, 'Lewitacja', 'Postać potrafi unosić się nisko nad ziemią. Zasady dotyczące lewitacji znajdziesz w Rozdziale VI: Walka, obrażenia i nich.', 'Postać potrafi unosić się nad ziemią', '', ''],
            [31, 'Łotrzyk', 'Bohater jest blisko związany ze światem przestępczym. Otrzymuje modyfikator +10 do testów plotkowania i przekonywania w kontaktach z przedstawicielami przestępczego półświatka.', '+10 do plotkowania i przekonywania w półświadku', '', ''],
            [32, 'Magia czarnoksięska', 'Twój Bohater poznał tajniki jednej z zakazanych tradycji magicznych. Podobnie jak w przypadku magii tajemnej, zgłębianie sekretów magii czarnoksięskiej wymaga poświęcenia i wyboru jednej z dostępnych mrocznych tradycji. Każda magia czarnoksięska jest oddzielną zdolnością. Na przykład magia czarnoksięska (Chaos) różni się od magii czarnoksięskiej (nekromancja). W kolejnych dodatkach znajdziesz informacje o innych rodzajach magii czarnoksięskiej, włącznie z wyszczególnieniem mocy bogów Chaosu: Nurgla. Slaanesha i Tzeentcha. Znajomość magii czarnoksięskiej pozwala na rzucanie czarów z określonej tradycji. Szczegółowe zasady rzucania zaklęć znajdziesz w Rozdziale VII: Magia.', '', '', ''],
            [33, 'Magia kapłańska', 'Bohater jest tak żarliwym wyznawcą jakiegoś bóstwa, że dzięki jego modlitwom zdarzają się rzeczy nadprzyrodzone. Zgłębianie tajemnic boga wymaga fanatycznego poświęcenia i zaangażowania. Bohater musi wybrać jednego boga, a w konsekwencji także jedną z magii kapłańskich. Każda magia kapłańska jest oddzielną zdolnością magiczną, pozwalającą na rzucanie czarów z dziedziny określonego bóstwa. Na przykład magia kapłańska (dziedzina Sigmara) różni się od magii kapłańskiej (dziedzina Ulryka). Każde z większych bóstw w Starym Święcie posiada własny kult, który naucza magii kapłańskiej. Są to Świątynie: Mananna, Morra, Mynnidii, Ranalda. Sigmara, Shallyi, Taala i Rhyi, Ulryka oraz Vereny. Znajomość magii kapłańskiej pozwala na rzucanie czarów z okieśluuej dziedziny. Szczegółowe zasady izuv.ni a zaklęć znajdziesz w Rozdziale VII: Magia.', '', '', ''],
            [34, 'Magia powszechna', 'Bohater potrafi rzucać zaklęcia, które są powszechnie używane przez czarodziejowi kapłanów. Magia powszechna obejmuje wybór czarów, z których każdy jest osobną zdolnością. Na przykład magia powszechna (rozproszenie magii) i magia powszechna (podniebny chód) to odrębne zdolności. Najczęściej wykorzystywane czary z magii powszechnej to: dotyk na odległość, magiczny alarm, magiczna broń, magiczny zamek, pancerz Eteru, podniebny chód, rozproszenie magii oraz uciszenie. Szczegółowe informacje na temat magii powszechnej i opis poszczególnych czarów znajdziesz w Rozdziale VII: Magia. Zdolncść magia powszechna wymaga uprzedniego posiadania zdolności magia prosta.', '', '', ''],
            [35, 'Magia prosta', 'Bohater poznał podstawowe tajniki rzucania czarów. Magia prosta, podobnie jak magia tajemna, obejmuje kilka zdolności. Każdy rodzaj magii prostej jest traktowany jako oddzielna zdolność magiczna Na przykład magia prosta (tajemna) i magia prosta (kapłańska) to odrębne zdolności. Znajomość dowolnego rodzaju magii prostej i posiadanie cechy Magia przynajmniej na poziomie 1 pozwala na rzucanie czarów z odpowiedniej listy zaklęć. Istnieją trzy podstawowe rodzaje magii prostej: gusła, kapłańska i tajemn;. Szczegółowe zasady rzucania zaklęć znajdziesz w Rozdziale VII: Magia.', '', '', ''],
            [36, 'Magia tajemna', 'Bohater pozrał tajniki jednej z kilku tradycji magicznych znanych w Imperium. Magia tajemna wymaga absolutnego poświęcenia i długotrwałych studiów. W konsekwencji Bohater musi dokonać wyboru jednej z dostępnych tradycji i nie będzie mógł uczyć się innych. Każdy rodzaj magii tajemnej jest oddzielną zdolnością. Na przykład magia tajemna (zwierzęta) różni się od magu tajemnej (ogień). W Imperium istnieje osiem Kolegiów Magii, z których każde naucza odrębnej Tradycji, czyli odmiennej magii tajemnej. Są to Tradycje: Cienia, Metalu. Niebios, Ognia, Śmierci, Światła, Zwierząt i Życia. Znajomość magii tajemnej pozwala na rzucanie czarów należących do określonej tradycji. Szczegółowe zasady rzucania zaklęć znajdziesz w Rozdziale VII: Magia.', '', '', ''],
            [37, 'Medytacja', 'Bohater potrafi skupić się na własnym wnętrzu i wejść w głęboki trans, ignorując doznania ze świata zewnętrznego. Podczas odprawiania rytuału magicznego BG otrzymuje modyfikator do poziomu mocy czaru równy wartości jego cechy Magia.', 'Poziom mocy rytuału +Mag BG', '', ''],
            [38, 'Morderczy atak', 'Dzięki znajomości podstaw anatomii Bohater potrafi wymierzyć atak w newralgiczną część ciała przeciwnika. Zwiększa to o 1 Wartość Krytyczną wszystkich trafień krytycznych zadanych przez BG.', 'Trafienie krytyczne zadane bronią w walce wręcz +1', '', ''],
            [39, 'Morderczy pocisk', 'Bohater specjalizuje się w czarach typu „magiczny pocisk". Otrzymuje modyfikator + 1 do rzutów na obrażenia, gdy atakuje czarami tego typu.', 'Zaklęcia typu "magiczny pocisk" obrażenia +1', '', ''],
            [40, 'Naśladowca', 'Bohater potrafi bezbłędnie naśladować różne odgłosy. Otrzymuje modyfikator + 10 do testów: kuglarstwa (aktorstwo, błaznowanie, gawędziarstwo i komedianctwo), charakteryzacji (jeśli jednym z elementów przebrania jest naśladowanie głosu lub dźwięków) oraz znajomości języka, gdy próbuje udawać, że to jego język ojczysty.', '+10 do testów udawania kogoś', '', ''],
            [41, 'Niepokojący', 'Bohater ma w swoim wyglądzie coś takiego, że przeciwnicy stają się niespokojni. Widząc go. wrogowie muszą wykonać test Siły Woli. Nieudany test oznacza, że otrzymują modyfikator -10 do testów Walki Wręcz i Umiejętności Strzeleckich w czasie walki z Bohaterem. Podczas każdej kolejnej rundy mogą próbować przełamać swój lęk (wykonując kolejny test Siły Woli). Efekt mija, gdy jedna ze stron ucieknie z pola walki.', 'Test SW przeciwnika albo kara -10 do WW i US', '', ''],
            [42, 'Nieustraszony', 'Bohater nie odczuwa strachu. Może jest naprawdę odważny, a może po prostu szalony. Bez względu na przyczynę, jest odporny na Strach i w mniejszym stopniu ulega Grozie (wykonujesz rzut przeciw Grozie jako rzut przeciw Strachowi). Bohater jest również odporny na działanie umiejętności zastraszanie i zdoklności niepokojący. Szczegółowe zasady dotyczące wzbudzania Strachu i Grozy znajdziesz w Rozdziale IX: Mistrz Gry', 'Strach nie działa; Groza działa jak Strach', '', ''],
            [43, 'Niezwykle odporny', 'Bohater obdarzony jest wyjątkową odpornością. Otrzymuje +5 do Odporności, dodawane do początkowej wartości cechy Może 10 zmienić wartość Wytrzymałości, BG zgodnie z zasadami opisanymi na str. 19.', 'Odporność +5 na stałe', '5', '4'],
            [44, 'Obieżyświat', 'Bohater w swoim życiu wiele podróżował, zdobywając rozległą wiedzę. Otrzymuje modyfikator +10 do wszystkich testów wiedzy oraz znajomości języka.', '+10 do wiedzy i znajomości języka', '', ''],
            [45, 'Oburęczność', 'Bohater może używać obu rąk z jednakową sprawnością, nic otrzymując modyfikatora -20 do Walki Wręcz, gdy trzyma broń w słabszej ręce.', 'Brak kary dla broni w drugiej ręce', '', ''],
            [46, 'Odporność na Chaos', 'Bohater obdarzony jest naturalną odpornością na wpływ Chaosu. Otrzymuje modyfikator +10 do Siły Woli podczas testów przeciwko magii i efektom Chaosu. Jest również całkowicie odporny na mutaq’e Chaosu. Jednak nigdy nie będzie mógł rzucać czarów.', 'SW +10 przeciw Chaosowi i magii; brak mutacji', '', ''],
            [47, 'Odporność na choroby', 'Bohater jest obdarzony końskim zdrowiem. Otrzymuje modyfikttor +10 do Odporności podczas testów przeciwko chorobom.', '+10 do Odp przeciw chorobom', '', ''],
            [48, 'Odporność na magię', 'Bohater w naturalny sposób opiera się działaniu czarów. Otrzymuje modyfikator +10 do Siły Woli podczas testów przeciwko magii.', '+10 do SW przeciwko magii', '', ''],
            [49, 'Odporność na trucizny', 'Wyjątkowa odporność organizmu pozwala Bohaterowi na osłabienie działania trucizny. Otrzymuje modyfikator +10 do Odporności podczas testów przeciwko truciznom.', '+10 do Odp przeciwko truciznom', '', ''],
            [50, 'Odporność psychiczna', 'Bohater jest mniej podatny na efekt szokujących i przerażających wydarzeń. Do momentu uzbierania 8 Punktów Obłędu nic musisz testować, czy Bohater nabawił się choroby umysłu. Bohater popada w obłęd (wykazuje objawy pierwszej choroby umysłowej) dopiero po uzbieraniu 14 Punktów Obłędu.', 'Choroba umysłowa dopiero przy 14 PO', '', ''],
            [51, 'Odwaga', 'Bohater odznacza się wyjątkową odwagą. Otrzymuje modyfikator +10 do Siły Woli podczas testów przeciwko Strachowi i Grozie oraz zastraszaniu.', '+10 do SW przeciwko zastraszaniu Strachowi i Grozie', '', ''],
            [52, 'Ogłuszanie', 'Po udanym ataku bronią białą Bohater może zadeklarować próbę ogłuszenia przeciwnika, zamiast zadawać mu obrażenia. W takiej sytuacji należy wykonać przeciwstawny test Krzepy. Jeśli Bohater wygra, jego przeciwnik musi natychmiast wykonać test Odporności, dodając modyfikator +10 za każdy Punkt Zbroi hełmu lub osłony noszonej na głowie. Jeśli ten test będzie nieudany, przeciwnik zostaje ogłuszony na 1k10 rund. W tym czasie nic może podejmować żadnych akcji i nic może stosować umiejętności unik.', 'Przeciwstawny test K i Odp lub przeciwnik przez k10 rund nic nie robi', '', ''],
            [53, 'Opanowanie', 'Bohater nigdy nie traci zimnej krwi. Otrzymuje +5 do Siły Woli, dodawane do początkowej wartości cechy.', '+5 do SW na stałe', '5', '7'],
            [54, 'Ożywieniec', 'Postać jest nieumarłym stworem, przywróconym do życia za pomocą magii nekromanckiej (patrz Rozdział VII: Magia). Jest odporna na Strach, Grozę, trucizny, choroby oraz na wszystkie czary, umiejętności i zdolności, które wpływają na emocje i umysł.', 'Jesteś nieumarłym stworem!', '', ''],
            [55, 'Pancerz wiary', 'Dzięki żarliwej modlitwie Bohater potrafi skatecznie rzucać czary, nawet nosząc pancerz. Zdolność umożliwia dodanie +3 do ujemnego modyfikatora do poziomu mocy czaru, który związany jest noszeniem zbroi. Na przykład rzucanie czarów i jednoczesne zasłanianie się ciężką tarczą jest obciążone modyfikatorem -3. Zdolność pancerz wiary redukuje ten modyfikator do 0.', '+3 do rzucania zaklęć w zbroi', '', ''],
            [56, 'Poliglota', 'Bohater posiada naturalną zdolność uczenia się i zapamiętywania obcych języków. Otrzymuje modyfikator +10 do testów czytania i pisania oraz znajomości języka', '+10 do czytania i pisania oraz znajomości języka', '', ''],
            [57, 'Przemawianie', 'Gdy Bohater przemawia, potrafi skupić uwagę większej grupy słuchaczy. Wykorzystując przekonywanie, może oddziaływać na grupę osób 10 razy liczniejszą niż normalnie.', 'Oddziaływanie na grupę 10 razy większą niż normalnie; wymagane do Krasomówstwa', '', ''],
            [58, 'Przerażający', 'Wygląd postaci wywołuje przerażenie wśród obserwatorów. Swoim zachowaniem wzbudza Grozę, zgodnie z zasadami opisanymi w Rozdziale IX: Mistrz Gry.', 'Postać wzbudza Grozę!', '', ''],
            [59, 'Rozbrajanie', 'Po udanym ataku bronią białą. Bohater może podjąć próbę rozbrojenia przeciwnika, zamiast zadawać mu obrażenia. W takiej sytuacji należy wykonać przeciwstawny test Zręczncści. Jeśli Bohater wygra, jego przeciwnik zostaje rozbrojony i upuszcza broń. Broń można podnieść, wykonując akcję „użycie przedmiotu”. Jeśli przeciwnik wygra, utrzymuje broń w ręce. Nie możra rozbrajać przeciwnika, który walczy bronią naturalną (kły, pazary, itp.).', 'Po trafieniu przeciwstawny test Zr; wróg gubi broń', '', ''],
            [60, 'Silny Cios', 'Dzięki doświadczeniu nabytemu w wielu walkach Bohater potrafi precyzyjnie wymierzać ciosy w walce wręcz. Otrzymuje modyfikator + 1 do obrażeń zadawanych bronią białą.', 'Obrażenia w walce wręcz +1', '1', ''],
            [61, 'Straszny', 'Wygląd postaci wywołuje przestrach wśród obserwatorów. Swoim zachowaniem wzbudza Strach, zgodnie z zasadami opisanymi w Rozdziale IX: Mistrz Gry.', 'Postać wzbudza Strach!', '', ''],
            [62, 'Strzał mierzony', 'Wykonując atak bronią strzelecką. Bohater potrafi skoncentrować się i znacznie lepiej wycelować. Po zadeklarowaniu akcji „wycelowanie" otrzymuje modyfikator +20 do Umiejętności Strzeleckich przy rzucie na trafienie, zamiast normalnego modyfikatora +10.', '+20 do US podczas akcji "celowanie"', '', ''],
            [63, 'Strzał precyzyjny', 'Wykonując atak bronią strzelecką. Bohater potrafi precyzyjnie wymierzyć strzał, który zadaje dodatkowe obrażenia. Otrzymuje modyfikator +1 do rzutów na obrażenia podczas ataku z użyciem broni strzeleckiej.', 'Obrażenia broni strzeleckich +1', '', ''],
            [64, 'Strzał przebijający', 'Bohater potrafi znaleźć odsłoniętą szczelinę w pancerzu przeciwnika. Po udanym ataku bronią strzelecką może zignorować 1 Punkt Zbroi przeciwnika. Jeśli przeciwnik nie nosi zbroi, ta zdolność jest nieskuteczna.', 'Pociski ignorują 1 PZ celu', '', ''],
            [65, 'Strzelec wyborowy', 'Bohater potrafi wyjątkowo celnie strzelać. Otrzymuje +5 do Umiejętności Strzeleckich, dodawane do początkowej wartości cechy.', '+5 do US na stałe', '5', '2'],
            [66, 'Szał bojowy', 'W trakcie walki Bohater potrafi wpaść w szał bojowy. Przez jedną rundę musi się doprowadzić do wściekłości (wyjąc, gryząc tarczę, bijac się w piersi, itd.). W następnej rundzie jego pierwotna natura bierze górę, zapewniając modyfikator + 10 do testów Siły Woli i Krzepy, (także +1 do Siły, czyli zadawanych obrażeń), przy jednoczesnym modyfikatorze -10 do testów Inteligencji i Walki Wręcz. Podczas walki zawsze atakuje najbliższego przeciwnika, wykonując „szarżę" lub „szaleńczy atak", nie może uciekać ani wykonywać akcji „odwrót". BG pozostaje pod wpływem szału bojowego do końca starcia.', '+10 do SW i K;-10 do WW i US; atak zawsze szarżą lub szaleńczym atakiem; nie można wykonywać odwrotu', '', ''],
            [67, 'Szczęście', 'Bohater jest nieprawdopodobnym szczęściarzem. Wydaje się wychodzić obronną ręką z najgorszych opresji. Każdego dnia dostaje dodatkowy Punkt Szczęścia. Szczegółowe zasady przyznawania i wydawania Punktów Szczęścia znajdziesz w Rozdziale VI: Walka, obrażenia i ruch.', '+1 punkt szczęścia dziennie', '', ''],
            [68, 'Szósty zmysł', 'Bohater jest niezwykle czujny i niemal instynktownie wyczuwa zagrożenie. W przypadku zasadzki lub innego zagrożenia Mistrz Gry może wykonać tajny test Siły Woli Bohatera. Jeśli test okaże się udany. Mistrz Gry powinien Cię poinformować, że Twój Bohater ma złe przeczucie albo wrażenie, że jest obserwowany. Dzięki temu BG obdarzony szóstym zmysłem może uniknąć zaskoczenia w początkowej fazie walki.', 'Wyczucie zasadzek test SW', '', ''],
            [69, 'Szybki refleks', 'Bohater jest obdarzony wspaniałym refleksem. Otrzymuje + 5 do Zręczności, dodawane do początkowej wartości cechy.', '+5 do Zr na stałe', '5', '5'],
            [70, 'Szybkie wyciągnięcie', 'Dzięki tej zdolności Bohater potrafi szybko zareagować, błyskawicznie dobywając broni lub wyciągając inny przedmiot zza pasa lub z kieszeni. Raz na rundę może użyć akcji „użycie przedmiotu" jako akcji natychmiastowej.', 'Dobycie broni jako akcja natychmiastowa', '', ''],
            [71, 'Talent artystyczny', 'Bohater potrafi tworzyć dzieła sztuki. Otrzymuje modyfikator +20 do testów rzemiosła (sztuka) oraz modyfikator +10 do testów wyceny przy szacowaniu wartości dzieł sztuki.', '+20 do rzemiosła(sztuka); +10 do wyceny dzieł sztuki', '', ''],
            [72, 'Twardziel', 'Bohater jest wyjątkowo odporny na ból i zranienia. Otrzymuje + 1 do Żywotności, dodawane do początkowej wartości cechy.', '+1 do Żywotności na stałe', '1', '10'],
            [73, 'Ulicznik', 'Bohater wychował się w mieście i z łatwością orientuje się w terenie zabudowanym. Otrzymuje modyfikator +10 do testów skradania się i ukrywania się w mieście.', '+10 do skradania się i ukrywania w mieście', '', ''],
            [74, 'Urodzony wojownik', 'Bohater wyjątkowo sprawnie posługuje się bronią białą. Otrzymuje +5 do Walki Wręcz, dodawane do początkowej wartości cechy.', '+5 do WW na stałe', '5', '1'],
            [75, 'Wędrowiec', 'Bohater wychował się na wsi i z łatwością orientuje się w terenie wiejskim. Otrzymuje modyfikator +10 do testów skradania się i ukrywania się na terenach poza miastem.', '+10 do skradania się i ukrywania poza miastem', '', ''],
            [76, 'Widzenie w ciemności', 'Bohater dysponuje zdolnością wyraźnego widzenia przy oświetleniu porównywalnym ze światłem gwiazd. Zasięg wzroku w takich warunkach wynosi 30 metrów. Zdolność jest bezużyteczna w całkowitej ciemności.', 'Widzenie w ciemności do 30m', '', ''],
            [77, 'Woltyżerka', 'Bohater potrafi dokonywać niewiarygodnych wyczynów podczas jazdy konnej. Potrafi stać na rękach na grzbiecie galopującego wierzchowca, przeskakiwać z jednego konia na drugiego, zeskakiwać w pełnym biegu, itp. Bohater wykonuje testy jeździectwa tylko w najbardziej ekstremalnych sytuacjach, a i wtedy otrzymu c modyfikator + 10 do testów tej umiejętności.', '+10 do jeździectwa; testy w ekstremalnych warunkach', '', ''],
            [78, 'Wyczucie kierunku', 'Bohater instynktownie potrafi określać strony świata i orientować się w przestrzeni. Prawic nigdy się nie gubi i bez wahania potrafi wskazać kierunek północny. Dodatkowo otrzymuje modyfikator + 10 do testów nawigacji.', '+10 do nawigacji; naturalny kompas', '', ''],
            [79, 'Wykrywanie pułapek', 'Bohater jest ekspertem w wykrywaniu i rozbrajaniu pułapek. Otrzymuje modyfikator +10 do testów spostrzegawczości i otwierania zamków związanych z wykrywaniem i unieszkodliwianiem pułapek.', '+10 do spostrzegawczości i otwierania pułapek', '', ''],
            [80, 'Wyostrzone zmysły', 'Bohater posiada wyjątkowo wyczulone zmysły. Otrzymuje modyfikator +20 do wszystkich testów spostrzegawczości.', '+20 do spostrzegawczości', '', ''],
            [81, 'Zapasy', 'Bohater wyjątkowo dobrze walczy bez broni. Wykonując chwyt, otrzymuje modyfikator +10 do Walki Wręcz. Dodatkowo otrzymuje modyfikator +10 do Krzepy, gdy chwyta przeciwnika lub gdy wyzwala się z uścisku.', '+10 do WW i K podczas chwytu', '', ''],
            [82, 'Zapiekła nienawiść', 'Bohater podziela głęboko zakorzenioną wśród swojego ludu wrogość wobec wszystkich zielonoskórych. Ta wiekowa już tradycja napełnia go taką nienawiścią, że otrzymuje modyfikator +5 do Walki Wręcz, gdy atakuje gobliny, orki i hobgobliny.', '+5 do WW przeciw Zielonoskórym', '', ''],
            [83, 'Zmysł magii', 'Bohater potrafi umiejętnie manipulować Wiatrami Magii. Otrzymuje modyfikator +10 do testów splatania magii oraz wykrywania magii.', '+10 do testów splatania magii', '', ''],
            [84, 'Żyłka handlowa', 'Bohater potrafi sprzedać niemal wszystko. Otrzymuje modyfikator +10 do testów targowania i wyceny.', '+10 do testów targowania i wyceny', '', ''],
        ];
    }
}