import { describe, expect, it } from "vitest";
import { resolveCharacterAssetSource } from "@/lib/characterAssets";

describe("character assets", () => {
  it("uses only the URL generated by the backend", () => {
    expect(
      resolveCharacterAssetSource(
        {
          assets: {
            token: {
              mediaAssetId: 37,
              url: "https://media.example.test/token",
            },
          },
        },
        "token",
      ),
    ).toBe("https://media.example.test/token");
  });

  it("does not interpret a provider public ID in the browser", () => {
    expect(
      resolveCharacterAssetSource(
        { publicId: "character-assets/000037/token" },
        "token",
      ),
    ).toBe("");
  });

  it("uses the canonical URL when a normalized character has no asset set", () => {
    const imageUrl =
      "https://5e.tools/img/bestiary/tokens/DMG/Avatar%20of%20Death.webp";

    expect(
      resolveCharacterAssetSource(
        { assets: {}, avatarUrl: imageUrl },
        "avatar",
      ),
    ).toBe(imageUrl);
  });
});
