const messages = {
  pl: {
    title: "Czat kampanii",
    collapse: "Zwiń czat",
    expand: "Otwórz czat",
    live: "Połączono na żywo",
    syncing: "Synchronizacja…",
    reconnecting: "Ponowne łączenie…",
    offline: "Czat offline",
    refresh: "Odśwież",
    retry: "Połącz ponownie",
    older: "Wczytaj starsze wiadomości",
    loading: "Wczytywanie wiadomości…",
    empty: "Nie ma jeszcze wiadomości. Rozpocznij rozmowę.",
    placeholder: "Napisz wiadomość…",
    send: "Wyślij",
    sending: "Wysyłanie…",
    newMessage: "Nowa",
    readOnly: "Masz dostęp tylko do odczytu.",
    counter: "{count}/{max}",
    roll: {
      summary: "{name} rzuca {formula}",
      flavor: "Rzut kośćmi",
      total: "Wynik",
      subtotal: "Suma częściowa",
      expand: "Pokaż wyniki poszczególnych kości",
      dice: "Wyniki kości",
    },
    magic: {
      flavor: "Rzucanie czaru",
      castingNumber: "WPM",
      powerDice: "Kości Mocy",
      chaosDice: "Kości Chaosu",
      modifier: "Modyfikator",
      powerTotal: "Poziom mocy",
      result: "Wynik",
      success: "Sukces zaklęcia",
      failure: "Porażka zaklęcia",
      automaticFailureLabel: "Jedynki",
      automaticFailure: "Automatyczna porażka · wymagany test SW",
      channel: "Splatanie",
      channelSuccess: "Sukces · rzut {roll} · premia +{bonus}",
      channelFailure: "Porażka · rzut {roll} · premia +{bonus}",
      ingredient: "Składnik",
      consumed: "zużyty",
      notConsumed: "niezużyty",
      curse: "Przekleństwo Tzeentcha",
      noCurse: "Brak",
      targets: "Cele",
      defense: "Obrona celu",
      effect: "Opis zaklęcia",
      severity: {
        minor: "Pomniejsza manifestacja",
        major: "Poważna manifestacja",
        catastrophic: "Katastrofalna manifestacja",
        undefined: "Rozstrzyga MG",
      },
    },
    errors: {
      network: "Nie udało się połączyć z czatem.",
      offline:
        "Czat jest chwilowo offline. Wiadomość można ponowić po połączeniu.",
      forbidden: "Nie masz dostępu do czatu tej kampanii.",
      rate_limited: "Wysyłasz zbyt szybko. Poczekaj chwilę.",
      validation_failed: "Wiadomość jest pusta lub zbyt długa.",
      generic: "Nie udało się obsłużyć wiadomości.",
    },
  },
  en: {
    title: "Campaign chat",
    collapse: "Collapse chat",
    expand: "Open chat",
    live: "Live connection",
    syncing: "Synchronizing…",
    reconnecting: "Reconnecting…",
    offline: "Chat offline",
    refresh: "Refresh",
    retry: "Reconnect",
    older: "Load older messages",
    loading: "Loading messages…",
    empty: "No messages yet. Start the conversation.",
    placeholder: "Write a message…",
    send: "Send",
    sending: "Sending…",
    newMessage: "New",
    readOnly: "You have read-only access.",
    counter: "{count}/{max}",
    roll: {
      summary: "{name} rolls {formula}",
      flavor: "Dice roll",
      total: "Total",
      subtotal: "Subtotal",
      expand: "Show individual dice results",
      dice: "Dice results",
    },
    magic: {
      flavor: "Spell cast",
      castingNumber: "CN",
      powerDice: "Power Dice",
      chaosDice: "Chaos Dice",
      modifier: "Modifier",
      powerTotal: "Power total",
      result: "Result",
      success: "Spell succeeds",
      failure: "Spell fails",
      automaticFailureLabel: "Ones",
      automaticFailure: "Automatic failure · Will Power test required",
      channel: "Channelling",
      channelSuccess: "Success · roll {roll} · bonus +{bonus}",
      channelFailure: "Failure · roll {roll} · bonus +{bonus}",
      ingredient: "Ingredient",
      consumed: "consumed",
      notConsumed: "not consumed",
      curse: "Tzeentch's Curse",
      noCurse: "None",
      targets: "Targets",
      defense: "Target defence",
      effect: "Spell description",
      severity: {
        minor: "Minor manifestation",
        major: "Major manifestation",
        catastrophic: "Catastrophic manifestation",
        undefined: "GM resolution required",
      },
    },
    errors: {
      network: "Could not connect to campaign chat.",
      offline: "Chat is temporarily offline. Retry after reconnecting.",
      forbidden: "You do not have access to this campaign chat.",
      rate_limited: "You are sending too quickly. Wait a moment.",
      validation_failed: "The message is empty or too long.",
      generic: "The chat operation failed.",
    },
  },
};

const pathValue = (source, path) =>
  String(path)
    .split(".")
    .reduce((value, part) => value?.[part], source);

export const campaignChatText = (locale, key, variables = {}) => {
  const language = String(locale || "pl")
    .toLowerCase()
    .startsWith("en")
    ? "en"
    : "pl";
  const template = pathValue(messages[language], key) || key;
  return Object.entries(variables).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    String(template),
  );
};
