export const emptyTemplate = () => ({
  ID: null,
  NAME: "",
  DESCRIPTION: "",
  DETAILS: "",
  ITEM_CLASS: "TOOL",
  ITEM_GENRE: "UTILITY",
  IMG_CLASS: "v0001",
  PRIZE: 0,
  CURRENCY: "wfrp_empire",
  CHARGE: 0,
  ATTRIBUTES: [],
  WEAPON: { TYPE: "", DAMAGE: "", RANGE: "" },
  MECHANICS: [],
  MECHANICS_MODE: "EXTEND",
});

export const emptyInstance = () => ({
  templateId: null,
  containerId: null,
  name: "",
  description: "",
  details: "",
  itemClass: "TOOL",
  itemGenre: "UTILITY",
  imgClass: "v0001",
  price: 0,
  currencyCode: "wfrp_empire",
  charge: 0,
  attributes: [],
});

export const emptyStackInstance = () => ({
  id: null,
  templateId: null,
  containerId: null,
  originalContainerId: null,
  name: "",
  description: "",
  details: "",
  itemClass: "TOOL",
  itemGenre: "UTILITY",
  imgClass: "v0001",
  price: 0,
  currencyCode: "wfrp_empire",
  charge: 0,
  attributes: [],
  weapon: { TYPE: "", DAMAGE: "", RANGE: "" },
});
