export const createCoreComputedPart1 = (runtime) => {
  return {
    ...runtime.mapState("shop", [
      "shopName",
      "shops",
      "activeShopId",
      "apiStatus",
      "loadingBuy",
      "loadingSell",
      "errorBuy",
      "errorSell",
      "tradeDataLoaded",
      "isGM",
      "gmMode",
      "walletBalances",
      "templateItems",
      "inventoryItems",
      "trashItems",
      "selectedBuyIds",
      "selectedSellIds",
      "selectedBuyQuantities",
      "selectedSellQuantities",
      "selectedTemplateId",
      "selectedTrashId",
      "selectedInventoryId",
      "catalogNodes",
      "worldProfiles",
      "shopProfiles",
      "shopSuggestions",
      "shopTemplateRecommendations",
      "shopEditorState",
      "context",
      "actors",
      "permissions",
      "lastTradeReceipt",
      "playerTransactions",
    ]),
    serverContainerState() {
      return this.$store.state.shop.containerState || null;
    },
    bgWalletBrass() {
      const currencyCode = String(
        this.activeSettlementCurrencyCode || "generic",
      ).toLowerCase();
      const balance = Number(this.walletBalances?.[currencyCode]);
      return Number.isFinite(balance)
        ? Math.max(0, balance)
        : Math.max(0, Number(this.$store.state.shop.bgWalletBrass || 0));
    },
    ...runtime.mapGetters("shop", [
      "buyItems",
      "sellItems",
      "buyListTitle",
      "sellListTitle",
      "buyButtonLabel",
      "sellButtonLabel",
      "buyTotalBrass",
      "sellTotalBrass",
      "buyHasSelection",
      "sellHasSelection",
      "selectedTemplate",
      "selectedTrash",
      "selectedInventory",
      "activeShopProfile",
      "selectedShopSuggestions",
    ]),
    tradeModalContentProps() {
      return {
        isGM: this.isGM,
        isAssortmentMode: this.isAssortmentMode,
        isAssortmentToolsMode: this.isAssortmentToolsMode,
        isShopAddEditMode: this.isShopAddEditMode,
        shopName: this.playerVisibleShopName,
        leftFlankButtons: this.leftFlankButtons,
        rightFlankButtons: this.rightFlankButtons,
        showFieldEditDialog: this.showFieldEditDialog,
        classEditMode: this.classEditMode,
        classEditType: this.classEditType,
        classEditTarget: this.classEditTarget,
        classEditDraftValue: this.classEditDraftValue,
        classEditSearch: this.classEditSearch,
        classEditSuggestions: this.classEditSuggestions,
        classEditValidationError: this.classEditValidationError,
        classEditItemClass: this.classEditItemClass,
        bgWalletBrass: this.bgWalletBrass,
        walletBalances: this.walletBalances,
        activeSettlementCurrencyCode: this.activeSettlementCurrencyCode,
        activeBgName: this.activeBgName,
        activeBgOwner: this.activeBgOwner,
        activeBgAvatar: this.activeBgAvatar,
        lastTradeReceipt: this.lastTradeReceipt,
        playerTransactions: this.playerTransactions,
        containerUndoStack: this.containerUndoStack,
        containerSelectOptions: this.containerSelectOptions,
        assortmentLeftItems: this.assortmentLeftItems,
        assortmentRightItems: this.assortmentRightItems,
        assortmentLeftSelectedKeys: this.assortmentLeftSelectedKeys,
        assortmentRightSelectedKeys: this.assortmentRightSelectedKeys,
        gmMoveItemOptions: this.gmMoveItemOptions,
        gmMoveQuantityEnabled: this.gmMoveQuantityEnabled,
        gmMoveQuantityMax: this.gmMoveQuantityMax,
        containerOverview: this.containerOverview,
        shopContainerOptions: this.shopContainerOptions,
        shopBuyItemOptions: this.shopBuyItemOptions,
        characterContainerOptions: this.characterContainerOptions,
        shopBuyQuantityEnabled: this.shopBuyQuantityEnabled,
        shopEditorShopOptions: this.shopEditorShopOptions,
        canDeleteActiveShop: this.canDeleteActiveShop,
        activeShopId: this.activeShopId,
        shopTypeOptions: this.shopTypeOptions,
        shopOwnerOptions: this.shopOwnerOptions,
        worldProfileOptions: this.worldProfileOptions,
        shopWorldProfileImpactText: this.shopWorldProfileImpactText,
        locationTypeOptions: this.locationTypeOptions,
        legalStatusOptions: this.legalStatusOptions,
        wealthTierOptions: this.wealthTierOptions,
        reputationOptions: this.reputationOptions,
        seasonalityOptions: this.seasonalityOptions,
        shopEditorForm: this.shopEditorForm,
        activeShopProfile: this.activeShopProfile,
        templateItems: this.templateItems,
        shopItems: this.$store.state.shop.shopItems || [],
        catalogNodes: this.catalogNodes,
        worldProfiles: this.worldProfiles,
        currencyDefinitions: this.$store.state.shop.currencyDefinitions || {},
        shopAutoTagsText: this.shopAutoTagsText,
        activeShopTypeNode: this.activeShopTypeNode,
        shopSuggestions: this.shopSuggestions,
        shopTemplateRecommendations: this.shopTemplateRecommendations,
        selectedSuggestionIds: this.selectedSuggestionIds,
        showShopActivationDialog: this.showShopActivationDialog,
        shopActivationOptions: this.shopActivationOptions,
        shopActivationActiveCount: this.shopActivationActiveCount,
        assortmentRollTarget: this.assortmentRollTarget,
        gmMoveQuantity: this.gmMoveQuantity,
        assortmentRollPreview: this.assortmentRollPreview,
        assortmentRollPreviewMeta: this.assortmentRollPreviewMeta,
        shopSuggestionReasonText: this.shopSuggestionReasonText,
        shopSuggestionReasonDetailsText: this.shopSuggestionReasonDetailsText,
        showBuyForm: this.showBuyForm,
        showSellForm: this.showSellForm,
        showSellAddForm: this.showSellAddForm,
        isTrashMode: this.isTrashMode,
        buyListTitle: this.buyListTitle,
        sellListTitle: this.sellListTitle,
        buyItems:
          this.isBuyDataLoading || this.errorBuy
            ? []
            : this.playerVisibleBuyItems,
        sellItems:
          this.isSellDataLoading || this.errorSell ? [] : this.visibleSellItems,
        trashZoneOwnerCode: this.trashZoneOwnerCode,
        inventoryOwnerCodeFilter: this.inventoryOwnerCodeFilter,
        inventoryOwnerFilterOptions: this.inventoryOwnerFilterOptions,
        trashZoneOptions: this.trashZoneOptions,
        trashSlotCapacity: runtime.PLAYER_TRASH_SLOT_CAPACITY,
        trashZoneLoad: this.activeTrashZoneCount,
        buyItemClass: this.buyItemClass,
        sellItemClass: this.sellItemClass,
        selectedBuyIds: this.selectedBuyIds,
        selectedSellIds: this.selectedSellIds,
        buyActId: this.buyActId,
        sellActId: this.sellActId,
        buyTotalBrass: this.isBuyDataLoading ? 0 : this.buyTotalBrass,
        sellTotalBrass: this.isSellDataLoading ? 0 : this.sellTotalBrass,
        buyActionLabel: this.buyActionLabel,
        sellActionLabel: this.sellActionLabel,
        buyActionEnabled: !this.isBuyDataLoading && this.buyActionEnabled,
        sellActionEnabled: !this.isSellDataLoading && this.sellActionEnabled,
        loadingBuy: this.isBuyDataLoading,
        loadingSell: this.isSellDataLoading,
        errorBuy: this.errorBuy,
        errorSell: this.errorSell,
        templateFormErrors: this.templateFormErrors,
        newTemplateFormErrors: this.newTemplateFormErrors,
        inventoryFormErrors: this.inventoryFormErrors,
        indFieldNames: this.indFieldNames,
        tempFieldNames: this.tempFieldNames,
        showClassEditDialog: this.showClassEditDialog,
        showWeaponStatsDialog: this.showWeaponStatsDialog,
        showOwnerOptDialog: this.showOwnerOptDialog,
        showItemDetailDialog: this.showItemDetailDialog,
        showSuggestionDetailDialog: this.showSuggestionDetailDialog,
        showAssortmentMergeDialog: this.showAssortmentMergeDialog,
        imgClassOptions: this.imgClassOptions,
        selectedImgClass: this.selectedImgClass,
        ownerOptOptions: this.ownerOptOptions,
        inventoryOwnerOptions: this.inventoryOwnerOptions,
        selectedOwnerOpt: this.selectedOwnerOpt,
        displayOwnerOpt: this.displayOwnerOpt,
        weaponStatsDraft: this.weaponStatsDraft,
        weaponStatsItemOptions: this.weaponStatsItemOptions,
        weaponFeatureOptions: this.weaponFeatureOptions,
        weaponStatsSourceType: this.weaponStatsSourceType,
        itemDetailItem: this.itemDetailItem,
        itemDetailDisplayName: this.itemDetailDisplayName,
        itemDetailChargeLabel: this.itemDetailChargeLabel,
        itemDetailSourceLabel: this.itemDetailSourceLabel,
        itemDetailCanEditNickname: this.itemDetailCanEditNickname,
        itemDetailNicknameModeLabel: this.itemDetailNicknameModeLabel,
        itemDetailPersonalCost: this.itemDetailPersonalCost,
        itemDetailPersonalCostRaw: this.itemDetailPersonalCostRaw,
        itemDetailCurrencyCode: this.itemDetailCurrencyCode,
        itemDetailCurrencyLabel: this.itemDetailCurrencyLabel,
        itemDetailChargeText: this.itemDetailChargeText,
        itemDetailMetaLines: this.itemDetailMetaLines,
        itemDetailMetaSections: this.itemDetailMetaSections,
        itemDetailImageSrc: this.itemDetailImageSrc,
        suggestionDetailEntry: this.suggestionDetailEntry,
        suggestionDetailVariantId: this.suggestionDetailVariantId,
        canMergeAssortmentSelection: this.canMergeAssortmentSelection,
        assortmentMergeFieldDefinitions: this.assortmentMergeFieldDefinitions,
        assortmentMergeLeftItem: this.assortmentMergeLeftItem,
        assortmentMergeRightItem: this.assortmentMergeRightItem,
        assortmentMergeChoices: this.assortmentMergeChoices,
        fieldInputType: this.fieldInputType,
        isReadOnlyField: this.isReadOnlyField,
        legacyIconClassForItem: this.legacyIconClassForItem,
        itemImageSrcForItem: this.itemImageSrcForItem,
        containerLabelById: this.containerLabelById,
        filteredContainerItems: this.filteredContainerItems,
        isContainerSelected: this.isContainerSelected,
        containerItemInlineLabel: this.containerItemInlineLabel,
        ownerOptDescription: this.ownerOptDescription,
        iconStyle: this.iconStyle,
        formatCoin: this.formatCoin,
        showTempHidden: this.showTempHidden,
        selectedBuyQuantityForItem: this.selectedBuyQuantityForItem,
        selectedSellQuantityForItem: this.selectedSellQuantityForItem,
        canAdjustBuySelectionQuantity: this.canAdjustBuySelectionQuantity,
        canAdjustSellSelectionQuantity: this.canAdjustSellSelectionQuantity,
        openAssortmentMergeDialog: this.openAssortmentMergeDialog,
        closeAssortmentMergeDialog: this.closeAssortmentMergeDialog,
        setAssortmentMergeChoice: this.setAssortmentMergeChoice,
        assortmentMergeChoiceFor: this.assortmentMergeChoiceFor,
        confirmAssortmentMergeDialog: this.confirmAssortmentMergeDialog,
        changeShopForEditor: this.handleShopEditorShopChange,
        createShopForEditor: this.handleCreateShop,
        deleteActiveShopForEditor: this.handleDeleteActiveShop,
        openShopActivationDialogForEditor: this.openShopActivationDialog,
        closeShopActivationDialog: this.closeShopActivationDialog,
        toggleShopActivationForEditor: this.handleToggleShopActivation,
        updateShopEditorField: this.handleShopEditorFieldUpdate,
        rollShopSignboard: this.handleRollShopSignboard,
        saveShopEditorProfile: this.handleShopEditorSave,
        generateShopSuggestions: this.handleGenerateShopSuggestions,
        loadMoreShopSuggestions: this.handleLoadMoreShopSuggestions,
        toggleShopSuggestion: this.handleToggleShopSuggestion,
        applySelectedShopSuggestions: this.handleApplySelectedShopSuggestions,
        applyAllShopSuggestions: this.handleApplyAllShopSuggestions,
        createDraftTemplatesFromSelected:
          this.handleCreateDraftTemplatesFromSelected,
        rollShopStarterAssortment: this.handleRollShopStarterAssortment,
        previewShopStarterAssortment: this.handlePreviewShopStarterAssortment,
        applyAssortmentRollPreview: this.handleApplyAssortmentRollPreview,
        setAssortmentRollTarget: this.handleSetAssortmentRollTarget,
        setGmMoveQuantity: this.handleSetGmMoveQuantity,
        retryTradeDataLoad: this.retryTradeDataLoad,
        iconSizeMin: runtime.tradeIconMinSize,
        iconSizeMax: runtime.tradeIconMaxSize,
        iconSizeDefault: runtime.legacyIconSize,
      };
    },
  };
};
