export const createCoreRootPart1 = (runtime) => {
  return {
    name: "ShopTradeModal",
    components: {
      TradeModalShell: runtime.TradeModalShell,
      TradeModalContent: runtime.TradeModalContent,
    },
    data() {
      return {
        tempFieldNames: [
          "ID",
          "NAME",
          "DESCRIPTION",
          "DETAILS",
          "ITEM_CLASS",
          "ITEM_ID",
          "ITEM_GENRE",
          "IMG_CLASS",
          "PRIZE",
          "CHARGE",
        ],
        indFieldNames: [
          "ID",
          "INV_ID",
          "IMG_CLASS",
          "ITEM_PLACE",
          "PERSONAL_PSEU",
          "PERSONAL_DESC",
          "PERSONAL_COST",
          "QUANTITY",
          "OWNER_OPT",
        ],
        templateForm: {},
        newTemplateForm: {},
        inventoryForm: {},
        templateFormErrors: {},
        newTemplateFormErrors: {},
        inventoryFormErrors: {},
        classEditType: null,
        classEditTarget: null,
        classEditDraftValue: "",
        classEditSearch: "",
        classEditValidationError: "",
        selectedImgClass: "",
        selectedOwnerOpt: "",
        weaponStatsDraft: runtime.emptyWeaponStatsDraft(),
        containerState: runtime.createContainerState(),
        containerInstanceMeta: {},
        containerUndoStack: [],
        assortmentSearch: "",
        assortmentLeftContainerId: null,
        assortmentRightContainerId: null,
        assortmentLeftSelectedKeys: [],
        assortmentRightSelectedKeys: [],
        assortmentLeftTab: "transfer",
        assortmentRightTab: "transfer",
        assortmentRollTarget: 12,
        gmMoveItemKey: "",
        gmMoveTargetContainerId: null,
        gmMoveQuantity: 1,
        shopBuyContainerId: null,
        shopBuyItemKey: "",
        shopBuyTargetContainerId: null,
        shopBuyQuantity: 1,
        assortmentRollPreview: [],
        assortmentRollPreviewMeta: null,
        trashZoneOwnerCode: runtime.TRASH_OWNER_GENERAL,
        modalObserver: null,
        showItemDetailDialog: false,
        showSuggestionDetailDialog: false,
        itemDetailItem: null,
        itemDetailSource: "",
        itemDetailNickname: "",
        itemDetailNicknameMode: "append",
        inventoryDetailSpriteUrl: "",
        suggestionDetailEntry: null,
        suggestionDetailVariantId: "",
        iconSize: runtime.legacyIconSize,
        walletAlert: "",
        walletAlertTimeout: null,
        walletAlertKey: 0,
        buyTransactionPending: false,
        sellTransactionPending: false,
        showShopActivationDialog: false,
        showPaymentConversionDialog: false,
        paymentQuotePending: false,
        paymentQuote: {},
        pendingPaymentPurchase: null,
      };
    },
    mounted() {
      this.deferTradeUiWork(runtime.ensureLegacyIconStyles);
      this.queueTradingDataLoad();
      this.resetNewTemplateForm();
      this.initModalScrollLock();
    },
    beforeUnmount() {
      this.teardownModalScrollLock();
    },
  };
};
